-- landing_dq.aro_cbr_agunan definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_agunan;

CREATE TABLE landing_dq.aro_cbr_agunan (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	cabang text NULL,
	nocif text NULL,
	noagunan text NULL,
	noloan text NULL,
	nilaiagunan text NULL,
	tglpenilaian text NULL,
	sid_datidua text NULL,
	jenisagunan text NULL,
	jenispengikatan text NULL,
	pemilikagunan text NULL,
	nobpkb text NULL,
	alamat text NULL,
	paripasu text NULL,
	ansuransi text NULL,
	tgl_pengikatan_agunan text NULL
);


-- landing_dq.aro_cbr_customer definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_customer;

CREATE TABLE landing_dq.aro_cbr_customer (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	nocustomer_baru text NULL,
	nocustomer_lama text NULL,
	jenis_customer text NULL,
	cabang text NULL,
	keterkaitan text NULL,
	golonganpemilik text NULL,
	lokasipenabung text NULL,
	namadebitur text NULL,
	alamat1 text NULL,
	alamat2 text NULL,
	kodepos text NULL,
	kelurahan text NULL,
	kecamatan text NULL,
	dati2debitur text NULL,
	status text NULL,
	keterangan_status text NULL,
	pendirian text NULL,
	tempatlahir text NULL,
	tgllahir text NULL,
	namaibukandung text NULL,
	jeniskelamin text NULL,
	jenisnasabah text NULL,
	tempat_bekerja_debitur text NULL,
	iddebitur text NULL,
	idjabatan text NULL,
	namapengurus text NULL,
	jeniskelaminpengurus text NULL,
	alamatpengurus1 text NULL,
	alamatpengurus2 text NULL,
	kota text NULL,
	kelurahanpengurus text NULL,
	kecamatanpengurus text NULL,
	idpengurus text NULL,
	kepemilikansaham text NULL,
	golongandebitur_sid text NULL,
	negara text NULL,
	bidangusaha text NULL,
	hub_bank text NULL,
	alamatkantor1 text NULL,
	alamatkantor2 text NULL,
	dati2debiturpengurus text NULL,
	jenispekerjaan text NULL,
	din text NULL,
	namaalias text NULL,
	npwp text NULL,
	kodearea text NULL,
	penghasilan_perbulan text NULL,
	sumber_penghasilan text NULL,
	jumlah_tangggungan text NULL,
	status_perkawinan text NULL,
	nik_pasangan text NULL,
	nama_pasangan text NULL,
	tgllahir_pasangan text NULL,
	nohp text NULL,
	notelp text NULL,
	createdate text NULL,
	updatedate text NULL
);


-- landing_dq.aro_cbr_deposito definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_deposito;

CREATE TABLE landing_dq.aro_cbr_deposito (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	nocif text NULL,
	golongandebitur text NULL,
	jenisbank text NULL,
	sandibank text NULL,
	cabang text NULL,
	norekening text NULL,
	produk_sukubunga text NULL,
	tglmulai text NULL,
	tgljatuhtempo text NULL,
	nominalblokir text NULL,
	nominal text NULL
);


-- landing_dq.aro_cbr_loan definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_loan;

CREATE TABLE landing_dq.aro_cbr_loan (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	norekeningbaru text NULL,
	norekeninglama text NULL,
	produk text NULL,
	nocustomer text NULL,
	periodebayarpokok text NULL,
	periodebayarbunga text NULL,
	kualitas text NULL,
	jangkawaktumulai text NULL,
	jangkawaktujatuhtempo text NULL,
	angsuranpokokpertama text NULL,
	plafondakad text NULL,
	plafondefektif text NULL,
	bakidebet text NULL,
	tunggakanpokok text NULL,
	akrubunga text NULL,
	flagstatus text NULL,
	sifatkredit text NULL,
	sifatkredit2 text NULL,
	jenispenggunaan text NULL,
	sumberdana text NULL,
	golkredit text NULL,
	orientasipenggunaan text NULL,
	sektorekonomi text NULL,
	sektorekonomi2 text NULL,
	jenisusaha text NULL,
	sifat_sukubunga text NULL,
	persensukubunga text NULL,
	jumlah_biaya text NULL,
	sisa_amortisasi text NULL,
	namabiaya text NULL,
	jumlah_fee text NULL,
	sisa_fee text NULL,
	nama_fee text NULL,
	cabang text NULL,
	noakad text NULL,
	tgl_macet text NULL,
	tgl_kondisi text NULL,
	portfoliocatid text NULL,
	creditcategoryid text NULL,
	lokasiproyek text NULL,
	"committed" text NULL,
	"uncommitted" text NULL,
	debiturcatid text NULL
);


-- landing_dq.aro_cbr_neraca definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_neraca;

CREATE TABLE landing_dq.aro_cbr_neraca (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	idakun text NULL,
	idinduk text NULL,
	noakun text NULL,
	namaakun text NULL,
	jenisakun text NULL,
	levelakun text NULL,
	saldoakhir001 text NULL
);


-- landing_dq.aro_cbr_tabungan definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_tabungan;

CREATE TABLE landing_dq.aro_cbr_tabungan (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	nocif text NULL,
	golongandebitur text NULL,
	jenisbank text NULL,
	sandibank text NULL,
	tglmulai text NULL,
	tglakhir text NULL,
	cabang text NULL,
	norekening text NULL,
	flag_status text NULL,
	sukubunga text NULL,
	nominalblokir text NULL,
	nominal text NULL
);


-- landing_dq.aro_cbr_tunggakan definition

-- Drop table

-- DROP TABLE landing_dq.aro_cbr_tunggakan;

CREATE TABLE landing_dq.aro_cbr_tunggakan (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'ARO'::text,
	norekening text NULL,
	angsuranke text NULL,
	tanggal text NULL,
	nilai_angsuran text NULL,
	tungakan_bunga text NULL,
	tunggakan_pokok text NULL
);


-- landing_dq.bss_account definition

-- Drop table

-- DROP TABLE landing_dq.bss_account;

CREATE TABLE landing_dq.bss_account (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_no text NULL,
	account_number text NULL,
	customer_no text NULL,
	prodccy text NULL,
	category text NULL,
	currency text NULL,
	mnemonic text NULL,
	limit_ref text NULL,
	online_actual_bal text NULL,
	credit_movement text NULL,
	debit_movement text NULL,
	date_time text NULL,
	co_code text NULL,
	curr_no text NULL,
	prk_ld_id text NULL,
	opening_date text NULL,
	locked_amount text NULL,
	alt_acct_id text NULL,
	posting_restrict text NULL,
	condition_group text NULL,
	customer text NULL,
	account_title_1 text NULL,
	account_title_2 text NULL,
	short_title text NULL,
	position_type text NULL,
	currency_market text NULL,
	account_officer text NULL,
	other_officer text NULL,
	reconcile_acct text NULL,
	interest_liqu_acct text NULL,
	interest_comp_acct text NULL,
	int_no_booking text NULL,
	referal_code text NULL,
	waive_ledger_fee text NULL,
	ac_sta_status text NULL,
	charge_code text NULL,
	charge_amount text NULL,
	admin_fee_code text NULL,
	admin_fee_chrg text NULL,
	ld_acct_officer text NULL,
	az_value_date text NULL,
	az_matur_date text NULL,
	az_tenor text NULL,
	lbu_pfolio text NULL,
	sid_kat_deb text NULL,
	lbu_sifat_kred text NULL,
	lbu_sektor_eko text NULL,
	lbu_kat_ukur text NULL,
	lbu_jenis_peng text NULL,
	lbu_or_guna text NULL,
	sid_sifat_kredi text NULL,
	sid_jenis_peng text NULL,
	nil_proyek_bi text NULL,
	sid_lokasi_pryk text NULL,
	last_version text NULL,
	otor_version text NULL,
	l_flag_no_rwd text NULL,
	l_no_atm text NULL,
	l_atm_date text NULL,
	inactiv_marker text NULL,
	open_actual_bal text NULL,
	open_cleared_bal text NULL,
	online_cleared_bal text NULL,
	working_balance text NULL,
	date_last_cr_cust text NULL,
	amnt_last_cr_cust text NULL,
	tran_last_cr_cust text NULL,
	date_last_cr_auto text NULL,
	amnt_last_cr_auto text NULL,
	tran_last_cr_auto text NULL,
	date_last_cr_bank text NULL,
	amnt_last_cr_bank text NULL,
	tran_last_cr_bank text NULL,
	date_last_dr_cust text NULL,
	amnt_last_dr_cust text NULL,
	tran_last_dr_cust text NULL,
	date_last_dr_auto text NULL,
	amnt_last_dr_auto text NULL,
	tran_last_dr_auto text NULL,
	date_last_dr_bank text NULL,
	amnt_last_dr_bank text NULL,
	tran_last_dr_bank text NULL,
	cap_date_charge text NULL,
	cap_date_cr_int text NULL,
	cap_date_c2_int text NULL,
	cap_date_dr_int text NULL,
	cap_date_d2_int text NULL,
	cap_back_value text NULL,
	accr_chg_categ text NULL,
	accr_chg_trans text NULL,
	accr_chg_amount text NULL,
	accr_chg_susp text NULL,
	accr_cr_categ text NULL,
	accr_cr_trans text NULL,
	accr_cr_amount text NULL,
	accr_cr_susp text NULL,
	accr_cr2_categ text NULL,
	accr_cr2_trans text NULL,
	accr_cr2_amount text NULL,
	accr_cr2_susp text NULL,
	accr_dr_categ text NULL,
	accr_dr_trans text NULL,
	accr_dr_amount text NULL,
	accr_dr_susp text NULL,
	accr_dr2_categ text NULL,
	accr_dr2_trans text NULL,
	accr_dr2_amount text NULL,
	accr_dr2_susp text NULL,
	consol_key text NULL,
	int_liqu_type text NULL,
	int_liqu_acct text NULL,
	int_liq_ccy text NULL,
	passbook text NULL,
	start_year_bal text NULL,
	value_date text NULL,
	value_dated_bal text NULL,
	contingent_bal_cr text NULL,
	contingent_bal_dr text NULL,
	open_category text NULL,
	open_val_dated_bal text NULL,
	acct_credit_int text NULL,
	acct_debit_int text NULL,
	link_to_limit text NULL,
	closure_date text NULL,
	locked_with_limit text NULL,
	charge_account text NULL,
	charge_ccy text NULL,
	charge_mkt text NULL,
	interest_ccy text NULL,
	interest_mkt text NULL,
	con_charge_accr text NULL,
	con_interest_accr text NULL,
	alt_acct_type text NULL,
	premium_type text NULL,
	cap_date_prm text NULL,
	premium_freq text NULL,
	apr text NULL,
	joint_holder text NULL,
	relation_code text NULL,
	joint_notes text NULL,
	allow_netting text NULL,
	ledg_reco_with text NULL,
	stmt_reco_with text NULL,
	our_ext_acct_no text NULL,
	reco_tolerance text NULL,
	pending_id text NULL,
	total_pending text NULL,
	stock_control_type text NULL,
	serial_no_format text NULL,
	auto_pay_acct text NULL,
	orig_ccy_payment text NULL,
	auto_rec_ccy text NULL,
	original_acct text NULL,
	from_date text NULL,
	dispo_officer text NULL,
	tax_suspend text NULL,
	tax_at_settle text NULL,
	ica_main_account text NULL,
	ica_distrib_ratio text NULL,
	ica_main_acct_ind text NULL,
	ica_distrib_type text NULL,
	ica_post_interest text NULL,
	ica_main_ratio text NULL,
	ica_new_main_acc text NULL,
	ica_start_date text NULL,
	ica_add_remove text NULL,
	ica_back_value text NULL,
	ica_main_acct text NULL,
	ica_main_date text NULL,
	liquidation_mode text NULL,
	overdue_status text NULL,
	hvt_flag text NULL,
	single_limit text NULL,
	contingent_int text NULL,
	all_in_one_product text NULL,
	er_value_date text NULL,
	er_balance text NULL,
	ep_balance text NULL,
	sb_group_id text NULL,
	open_available_bal text NULL,
	available_date text NULL,
	av_auth_db_mvmt text NULL,
	av_nau_db_mvmt text NULL,
	av_auth_cr_mvmt text NULL,
	av_nau_cr_mvmt text NULL,
	available_bal text NULL,
	forward_mvmts text NULL,
	credit_check text NULL,
	available_bal_upd text NULL,
	consolidate_ent text NULL,
	max_sub_account text NULL,
	master_account text NULL,
	lock_inc_this_mvmt text NULL,
	closed_online text NULL,
	next_af_date text NULL,
	next_acct_cap text NULL,
	next_exp_date text NULL,
	date_last_update text NULL,
	next_stmt_date text NULL,
	exposure_dates text NULL,
	portfolio_no text NULL,
	shadow_account text NULL,
	fwd_entry_hold text NULL,
	first_af_date text NULL,
	cash_pool_group text NULL,
	open_asset_type text NULL,
	last_com_chg_date text NULL,
	ic_charge_id text NULL,
	ic_next_cap_date text NULL,
	ic_product text NULL,
	ic_lst_prod_cap text NULL,
	arrangement_id text NULL,
	acc_deb_limit text NULL,
	mandate_appl text NULL,
	mandate_reg text NULL,
	mandate_record text NULL,
	dr_adj_amount text NULL,
	dr2_adj_amount text NULL,
	cr_adj_amount text NULL,
	cr2_adj_amount text NULL,
	"event" text NULL,
	field text NULL,
	operand text NULL,
	value text NULL,
	mv_alert_res6 text NULL,
	mv_alert_res5 text NULL,
	mv_alert_res4 text NULL,
	mv_alert_res3 text NULL,
	mv_alert_res2 text NULL,
	mv_alert_res1 text NULL,
	request_id text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	asset_class text NULL,
	abit_acct_no text NULL,
	lbu_kat_ukur_ac text NULL,
	asset_class_flg text NULL,
	referal_id text NULL
);


-- landing_dq.bss_account_closed definition

-- Drop table

-- DROP TABLE landing_dq.bss_account_closed;

CREATE TABLE landing_dq.bss_account_closed (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	acct_close_date text NULL,
	account_no text NULL,
	opening_date text NULL,
	closure_inputter text NULL,
	closure_authoriser text NULL
);


-- landing_dq.bss_account_closure definition

-- Drop table

-- DROP TABLE landing_dq.bss_account_closure;

CREATE TABLE landing_dq.bss_account_closure (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_number text NULL,
	capital_date text NULL,
	open_actual_bal text NULL,
	open_cleared_bal text NULL,
	online_actual_bal text NULL,
	online_cleared_bal text NULL,
	standing_orders text NULL,
	uncleared_entries text NULL,
	total_cr_interest text NULL,
	total_dr_interest text NULL,
	total_charges text NULL,
	total_tax text NULL,
	acct_liquidated_to text NULL,
	currency text NULL,
	settlement_acct text NULL,
	cheques_os text NULL,
	bank_cards text NULL,
	cc_chgs_os text NULL,
	bc_bank_sort_code text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	acct_liqu_currency text NULL,
	posting_restrict text NULL,
	override text NULL,
	total_premium_amt text NULL,
	total_acc_amt text NULL,
	chargeable_amt text NULL,
	clo_charge_type text NULL,
	clo_charge_amt text NULL,
	clo_ch_tax_type text NULL,
	clo_ch_tax_amt text NULL,
	clo_charge_posted text NULL,
	acct_grp text NULL,
	acct_grp_cur text NULL,
	acct_grp_cond text NULL,
	cap_interest text NULL,
	total_pending_chg text NULL,
	total_pending_tax text NULL,
	reserved_5 text NULL,
	reserved_4 text NULL,
	reserved_3 text NULL,
	reserved_2 text NULL,
	total_pending_dr text NULL,
	local_ref text NULL,
	close_online text NULL,
	ft_id text NULL,
	close_mode text NULL,
	reserved_1 text NULL,
	lccy_charge_amt text NULL,
	acct_category text NULL,
	acct_grp_1 text NULL,
	acct_grp_cur_1 text NULL,
	acct_grp_cond_1 text NULL
);


-- landing_dq.bss_account_credit_int definition

-- Drop table

-- DROP TABLE landing_dq.bss_account_credit_int;

CREATE TABLE landing_dq.bss_account_credit_int (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	group_cy_date text NULL,
	interest_day_basis text NULL,
	cr_balance_type text NULL,
	cr_calcul_type text NULL,
	cr_minimum_bal text NULL,
	cr_basic_rate text NULL,
	cr_int_rate text NULL,
	cr_max_rate text NULL,
	cr_limit_amt text NULL,
	tax_key text NULL,
	cr_offset_only text NULL,
	cr_margin_oper text NULL,
	cr_margin_rate text NULL,
	cr_min_rate text NULL,
	cr2_balance_type text NULL,
	cr2_calcul_type text NULL,
	cr2_minimum_bal text NULL,
	cr2_offset_only text NULL,
	cr2_basic_rate text NULL,
	cr2_int_rate text NULL,
	cr2_margin_oper text NULL,
	cr2_max_rate text NULL,
	cr2_margin_rate text NULL,
	cr2_limit_amt text NULL,
	cr2_min_rate text NULL,
	interest_tax_min text NULL,
	net_tax text NULL,
	cr_min_bal_st_dte text NULL,
	cr_min_bal_ed_dte text NULL,
	cr_accr_open_ac text NULL,
	cr_accr_close_ac text NULL,
	cr2_min_bal_st_dte text NULL,
	cr2_min_bal_ed_dte text NULL,
	cr2_accr_open_ac text NULL,
	cr2_accr_close_ac text NULL,
	cr_min_value text NULL,
	cr_min_waive text NULL,
	cr2_min_value text NULL,
	cr2_min_waive text NULL,
	cr_zero_int_bal text NULL,
	cr_zero_int_oc text NULL,
	negative_rates text NULL,
	compound_type text NULL,
	compound_yield_method text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_account_prk definition

-- Drop table

-- DROP TABLE landing_dq.bss_account_prk;

CREATE TABLE landing_dq.bss_account_prk (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	limit_id text NULL,
	pastdue_days text NULL,
	asset_class text NULL,
	last_prov_date text NULL,
	last_prov_amt text NULL,
	last_calc_base_amt text NULL,
	last_overdrawn_amt text NULL,
	last_overdrawn_int text NULL,
	last_ft_number text NULL,
	last_ft_int_nab text NULL
);


-- landing_dq.bss_categ_entry definition

-- Drop table

-- DROP TABLE landing_dq.bss_categ_entry;

CREATE TABLE landing_dq.bss_categ_entry (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_number text NULL,
	company_code text NULL,
	amount_lcy text NULL,
	transaction_code text NULL,
	their_reference text NULL,
	pl_category text NULL,
	customer_id text NULL,
	exposure_date text NULL,
	currency_market text NULL,
	system_id text NULL,
	record_status text NULL,
	inputter text NULL,
	booking_date text NULL,
	value_date text NULL,
	consol_key text NULL,
	accounting_date text NULL,
	our_reference text NULL,
	currency text NULL,
	account_officer text NULL,
	product_category text NULL,
	trans_reference text NULL,
	authoriser text NULL,
	date_time text NULL,
	reversal_marker text NULL,
	department_code text NULL,
	narrative text NULL
);


-- landing_dq.bss_category definition

-- Drop table

-- DROP TABLE landing_dq.bss_category;

CREATE TABLE landing_dq.bss_category (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	description text NULL,
	short_name text NULL,
	system_ind text NULL,
	record_status text NULL,
	date_time text NULL,
	co_code text NULL,
	curr_no text NULL,
	category_code text NULL,
	ac_contingent text NULL,
	mnemonic text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_collateral definition

-- Drop table

-- DROP TABLE landing_dq.bss_collateral;

CREATE TABLE landing_dq.bss_collateral (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	collateral_type text NULL,
	description text NULL,
	currency text NULL,
	execution_value text NULL,
	central_bank_value text NULL,
	value_date text NULL,
	expiry_date text NULL,
	address text NULL,
	collateral_code text NULL,
	coll_address text NULL,
	legal_type text NULL,
	coll_dati2 text NULL,
	coll_peringkat text NULL,
	coll_paripasu text NULL,
	coll_penilai_in text NULL,
	review_date_fqu text NULL,
	application_id text NULL,
	lbu_penerbit text NULL,
	lbu_rating_lmbg text NULL,
	lbu_rating_date text NULL,
	coll_ownernm text NULL,
	coll_certnum text NULL,
	col_tgl_nil text NULL,
	coll_is_insured text NULL,
	col_nil_njop text NULL,
	col_bkt_milik text NULL,
	collateral_right text NULL,
	date_time text NULL,
	co_code text NULL,
	curr_no text NULL,
	gen_ledger_value text NULL,
	co_book text NULL,
	l_sifat_agunan text NULL,
	nominal_value text NULL,
	company text NULL,
	country text NULL,
	maximum_value text NULL,
	third_party_value text NULL,
	notes text NULL,
	coll_city text NULL,
	coll_province text NULL,
	land_size text NULL,
	build_size text NULL,
	insurance_comp text NULL,
	insurance_typ text NULL,
	insurance_amt text NULL,
	bank_name text NULL,
	bank_address text NULL,
	bank_branch text NULL,
	manufacturer text NULL,
	vehicle_model text NULL,
	vehicle_colour text NULL,
	manufacture_yr text NULL,
	police_num text NULL,
	coll_cond text NULL,
	dt_legal_date text NULL,
	col_nil_lik text NULL,
	col_no_ikat text NULL,
	col_tgl_jt_sert text NULL,
	appraisal_nm text NULL,
	appraisal_dt text NULL,
	appraisal_typ text NULL,
	ins_type_set text NULL,
	ins_dtexp_set text NULL,
	ins_nm_set text NULL,
	ins_no_set text NULL,
	ins_rate_set text NULL,
	ins_amt_set text NULL,
	ins_premi_set text NULL,
	ins_bnm_set text NULL,
	ins_tnor_set text NULL,
	ins_bbranch_set text NULL,
	ins_baddrs_set text NULL,
	ins_rsve1_set text NULL,
	ins_rsve2_set text NULL,
	dt_exp_hgb text NULL,
	mt_bukti_kios text NULL,
	luas_kios text NULL,
	sthuni text NULL,
	stkios text NULL,
	nama_pasar text NULL,
	jnspsr text NULL,
	l_no_kios text NULL,
	no_hak_land text NULL,
	st_dt_hak_land text NULL,
	mt_dt_hak_land text NULL,
	l_no_bangunan text NULL,
	bank_deposit text NULL,
	st_dt_deposit text NULL,
	mt_dt_deposit text NULL,
	ctcode text NULL,
	coll_id_agunan text NULL,
	owncode text NULL,
	l_type_he text NULL,
	l_bpkb_he text NULL,
	l_invoice_he text NULL,
	l_kwitansi_he text NULL,
	l_blangko_he text NULL,
	bpkb_tgl_vhc text NULL,
	stnk_no_vhc text NULL,
	track_name text NULL,
	jml_roda_vhc text NULL,
	cc_vhc text NULL,
	l_barang_dgg text NULL,
	l_piutang_dgg text NULL,
	taksasi_value text NULL,
	application text NULL,
	status text NULL,
	revalued_date text NULL,
	revalued_amount text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	alt_coll_id text NULL,
	ppap_flag text NULL
);


-- landing_dq.bss_collateral_right definition

-- Drop table

-- DROP TABLE landing_dq.bss_collateral_right;

CREATE TABLE landing_dq.bss_collateral_right (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	collateral_right text NULL,
	collateral_code text NULL,
	limit_reference text NULL,
	expiry_date text NULL,
	review_date_fqu text NULL,
	customer text NULL,
	limit_id text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	co_book text NULL,
	company text NULL,
	limit_ref_cust text NULL,
	percent_alloc text NULL,
	percentage_cover text NULL,
	validity_date text NULL,
	notary text NULL,
	notes text NULL,
	local_ref text NULL,
	status text NULL,
	os_percent_cover text NULL,
	alloc_work_id text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_company definition

-- Drop table

-- DROP TABLE landing_dq.bss_company;

CREATE TABLE landing_dq.bss_company (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	company_code text NULL,
	company_name text NULL,
	name_address text NULL,
	mnemonic text NULL,
	language_code text NULL,
	stat_rep_area text NULL,
	stat_rep_name text NULL,
	stat_rep_deliv text NULL,
	mgmt_rep_area text NULL,
	mgmt_rep_name text NULL,
	mgmt_rep_deliv text NULL,
	local_country text NULL,
	local_region text NULL,
	local_currency text NULL,
	rate_system text NULL,
	customer_company text NULL,
	default_rate_allow text NULL,
	fcy_conv_toler_min text NULL,
	fcy_conv_toler_max text NULL,
	charge_calculati text NULL,
	financial_year_e text NULL,
	inactivity_month text NULL,
	sub_division_cod text NULL,
	dc_tolerance_rat text NULL,
	dc_max_round_amt text NULL,
	separate_eod text NULL,
	official_holiday text NULL,
	branch_holiday text NULL,
	batch_holiday text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_currency definition

-- Drop table

-- DROP TABLE landing_dq.bss_currency;

CREATE TABLE landing_dq.bss_currency (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	mid_reval_rate text NULL,
	buy_rate text NULL,
	sell_rate text NULL,
	date_time text NULL,
	co_code text NULL,
	curr_no text NULL
);


-- landing_dq.bss_customer definition

-- Drop table

-- DROP TABLE landing_dq.bss_customer;

CREATE TABLE landing_dq.bss_customer (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	customer_no text NULL,
	mnemonic text NULL,
	name_1 text NULL,
	name_2 text NULL,
	street text NULL,
	sector text NULL,
	residence text NULL,
	legal_id text NULL,
	legal_doc_name text NULL,
	co_code text NULL,
	post_code text NULL,
	gender text NULL,
	date_of_birth text NULL,
	job_title text NULL,
	employers_name text NULL,
	ktp_kelurahan text NULL,
	ktp_kecamatan text NULL,
	mother_maid_nam text NULL,
	sid_din text NULL,
	sid_sektor_econ text NULL,
	sid_dati2debtor text NULL,
	sid_rating_deb text NULL,
	sid_lembaga text NULL,
	sid_go_public text NULL,
	sid_related text NULL,
	sid_gol_deb text NULL,
	sid_tmp_akte_ak text NULL,
	place_of_birth text NULL,
	peng_id text NULL,
	peng_nama text NULL,
	peng_jenis_kela text NULL,
	peng_npwp text NULL,
	peng_alamat text NULL,
	peng_dati2 text NULL,
	peng_kelurahan text NULL,
	peng_kecamatan text NULL,
	peng_pemilikan text NULL,
	peng_id_jabatan text NULL,
	cus_npwp text NULL,
	sid_gelar text NULL,
	lbu_gol_deb text NULL,
	no_akta_awal text NULL,
	tgl_akta_awal text NULL,
	no_akta_akhir text NULL,
	tgl_akta_akhir text NULL,
	sid_hub_bank text NULL,
	sid_kat_deb text NULL,
	sid_rating_tgl text NULL,
	short_name text NULL,
	phone_area text NULL,
	phone_1 text NULL,
	sms_1 text NULL,
	sid_group_id text NULL,
	sid_group_name text NULL,
	sid_melampaui text NULL,
	sid_melanggar text NULL,
	lbu_status_deb text NULL,
	date_time text NULL,
	curr_no text NULL,
	lbu_sandi_bank text NULL,
	company_book text NULL,
	nationality text NULL,
	asset_class text NULL,
	address text NULL,
	sid_id_debitur text NULL,
	badan_hukum text NULL,
	alt_cust_id text NULL,
	previous_name text NULL,
	ktp_rt text NULL,
	ktp_rw text NULL,
	account_officer text NULL,
	other_officer text NULL,
	given_names text NULL,
	family_name text NULL,
	duplicate_cif text NULL,
	dup_of_cust text NULL,
	inactive_cust text NULL,
	sid_dati2_lahir text NULL,
	religion text NULL,
	contact_person text NULL,
	con_phone text NULL,
	con_address text NULL,
	con_relation text NULL,
	customer_rating text NULL,
	industry text NULL,
	dhn_flag text NULL,
	ktp_addr_flag text NULL,
	marital_status text NULL,
	customer_status text NULL,
	customer_type text NULL,
	"language" text NULL,
	red_flag text NULL,
	dhn_date text NULL,
	town_country text NULL,
	ktp_provinsi text NULL,
	contact_date text NULL,
	kyc_jenis_peng text NULL,
	residence_status text NULL,
	kyc_sumber_dana text NULL,
	occupation text NULL,
	employers_add text NULL,
	employers_buss text NULL,
	fax_1 text NULL,
	home_street text NULL,
	home_kelurahan text NULL,
	home_kecamatan text NULL,
	home_rt text NULL,
	home_rw text NULL,
	home_provinsi text NULL,
	home_post_code text NULL,
	hm_town_country text NULL,
	off_street text NULL,
	off_town_city text NULL,
	off_provinsi text NULL,
	off_post_code text NULL,
	email_1 text NULL,
	legal_holder_name text NULL,
	legal_iss_auth text NULL,
	legal_iss_date text NULL,
	legal_exp_date text NULL,
	relation_code text NULL,
	rel_deliv_opt text NULL,
	role_more_info text NULL,
	customer_liability text NULL,
	parent_customer text NULL,
	rel_customer text NULL,
	revers_rel_code text NULL,
	"role" text NULL,
	role_notes text NULL,
	rel_to_parent text NULL,
	change_date text NULL,
	customer_since text NULL,
	interests text NULL,
	other_nationality text NULL,
	further_details text NULL,
	last_education text NULL,
	change_reason text NULL,
	no_of_dependents text NULL,
	domicile text NULL,
	pastimes text NULL,
	spoken_language text NULL,
	residence_type text NULL,
	residence_since text NULL,
	residence_value text NULL,
	mortgage_amt text NULL,
	residence_month text NULL,
	residence_year text NULL,
	comm_type text NULL,
	confid_txt text NULL,
	internet_banking_service text NULL,
	mobile_banking_service text NULL,
	pref_channel text NULL,
	kyc_relationship text NULL,
	last_kyc_review_date text NULL,
	risk_asset_type text NULL,
	aml_check text NULL,
	manual_risk_class text NULL,
	introducer text NULL,
	kyc_complete text NULL,
	auto_next_kyc_review_date text NULL,
	risk_level text NULL,
	aml_result text NULL,
	last_aml_result_date text NULL,
	risk_from_date text NULL,
	override_reason text NULL,
	kyc_cash_dep_li text NULL,
	kyc_cash_wd_fq text NULL,
	kyc_noncash_lim text NULL,
	kyc_noncash_fqu text NULL,
	kyc_cash_dep_fq text NULL,
	kyc_noncash_fq text NULL,
	kyc_cash_wd_lim text NULL,
	kyc_non_cash_wd text NULL,
	kyc_busi_lic_no text NULL,
	kyc_akte_no text NULL,
	kyc_revenue text NULL,
	comp_permit_no text NULL,
	kyc_cap_owner text NULL,
	company_bank text NULL,
	employment_status text NULL,
	employment_start text NULL,
	annual_bonus text NULL,
	net_monthly_out text NULL,
	salary_date_freq text NULL,
	fixed_allowance text NULL,
	kyc_income_src text NULL,
	kyc_intend_fund text NULL,
	salary text NULL,
	net_monthly_in text NULL,
	other_income text NULL,
	kyc_purpose_acc text NULL,
	no_of_wife text NULL,
	no_of_child text NULL,
	no_of_parents text NULL,
	ben_name text NULL,
	ben_jns_kelamin text NULL,
	ben_status text NULL,
	ben_alamat text NULL,
	ben_kelurahan text NULL,
	ben_kecamatan text NULL,
	ben_kota text NULL,
	ben_provinsi text NULL,
	ben_kodepos text NULL,
	ben_telephone text NULL,
	ben_handphone text NULL,
	ben_lahir_tmp text NULL,
	ben_lahir_tgl text NULL,
	ben_sumber_dana text NULL,
	ben_income text NULL,
	ben_jenis_peng text NULL,
	ben_info_lain text NULL,
	ben_corp_name text NULL,
	ben_usaha_bid text NULL,
	ben_corp_alamat text NULL,
	ben_corp_smb_dn text NULL,
	ben_corp_info text NULL,
	ben_corp_tp_dn text NULL,
	ben_usaha_btk text NULL,
	issue_cheques text NULL,
	vis_type text NULL,
	vis_comment text NULL,
	former_vis_type text NULL,
	tax_id text NULL,
	cr_profile_type text NULL,
	no_update_crm text NULL,
	atm_number text NULL,
	fdsl_crd_number text NULL,
	allow_bulk_process text NULL,
	vis_internal_review text NULL,
	cr_profile text NULL,
	credit_card text NULL,
	sid_jenis_usaha text NULL,
	sid_pihak_kait text NULL,
	sid_lokasi_pryk text NULL,
	bank_name text NULL,
	type_of_loan text NULL,
	loan_value text NULL,
	oth_acct_no text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	waive_tax_flag text NULL,
	cus_open_date text NULL,
	kyc_incom_rng text NULL,
	referal_id text NULL,
	spouse_id text NULL,
	spouse_name text NULL,
	spou_dt_of_birt text NULL,
	company_type text NULL,
	job_title_bo text NULL,
	occupation_bo text NULL,
	ben_in_rng_1 text NULL,
	ben_npwp text NULL,
	ben_nationality text NULL,
	home_dati_ii text NULL,
	ben_legal_id text NULL,
	ben_ldoc_name text NULL,
	title text NULL,
	term_id text NULL,
	sign_nama text NULL,
	sign_id_type text NULL,
	sign_id_no text NULL,
	sign_place_birt text NULL,
	sign_date_birth text NULL,
	sign_jenis_kela text NULL,
	sign_alamat text NULL,
	sign_rt text NULL,
	sign_rw text NULL,
	sign_kelurahan text NULL,
	sign_kecamatan text NULL,
	sign_town_count text NULL,
	sign_provinsi text NULL,
	sign_country text NULL,
	sign_marital text NULL,
	sign_job text NULL,
	sign_relation text NULL,
	l_pisah_harta text NULL
);


-- landing_dq.bss_de_address definition

-- Drop table

-- DROP TABLE landing_dq.bss_de_address;

CREATE TABLE landing_dq.bss_de_address (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	delivery_address text NULL,
	answerback text NULL,
	institution_code text NULL,
	country_code text NULL,
	authentication text NULL,
	short_name text NULL,
	name_1 text NULL,
	name_2 text NULL,
	street_addr text NULL,
	town_country text NULL,
	post_code text NULL,
	country text NULL
);


-- landing_dq.bss_eb_contract_balances definition

-- Drop table

-- DROP TABLE landing_dq.bss_eb_contract_balances;

CREATE TABLE landing_dq.bss_eb_contract_balances (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	accr_category text NULL,
	curr_asset_type text NULL,
	open_balance text NULL,
	currency text NULL,
	credit_mvmt text NULL,
	debit_mvmt text NULL,
	collateral text NULL,
	customer text NULL,
	co_code text NULL,
	type_sysdate text NULL,
	open_actual_bal text NULL
);


-- landing_dq.bss_funds_transfer definition

-- Drop table

-- DROP TABLE landing_dq.bss_funds_transfer;

CREATE TABLE landing_dq.bss_funds_transfer (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	debit_acct_no text NULL,
	credit_acct_no text NULL,
	debit_value_date text NULL,
	credit_value_date text NULL,
	credit_currency text NULL,
	debit_currency text NULL,
	credit_amount text NULL,
	debit_amount text NULL,
	transaction_type text NULL,
	ben_customer text NULL,
	ordering_cust text NULL,
	lld_tuj_trx text NULL,
	acct_with_bank text NULL,
	payment_details text NULL,
	ben_acct_no text NULL,
	currency_mkt_dr text NULL,
	debit_their_ref text NULL,
	credit_their_ref text NULL,
	currency_mkt_cr text NULL,
	processing_date text NULL,
	ordering_bank text NULL,
	charge_com_display text NULL,
	commission_code text NULL,
	charge_code text NULL,
	return_to_dept text NULL,
	fed_funds text NULL,
	position_type text NULL,
	last_version text NULL,
	amount_debited text NULL,
	amount_credited text NULL,
	credit_comp_code text NULL,
	debit_comp_code text NULL,
	loc_amt_debited text NULL,
	loc_amt_credited text NULL,
	dr_advice_reqd_y_n text NULL,
	cr_advice_reqd_y_n text NULL,
	tot_rec_comm text NULL,
	tot_rec_comm_lcl text NULL,
	tot_rec_chg text NULL,
	tot_rec_chg_lcl text NULL,
	rate_fixing text NULL,
	tot_rec_chg_crccy text NULL,
	tot_snd_chg_crccy text NULL,
	auth_date text NULL,
	round_type text NULL,
	stmt_nos text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	skn_flag text NULL,
	rtgs_flag text NULL,
	term_id text NULL,
	term_type text NULL,
	card_no text NULL,
	recipt_no text NULL,
	otor_version text NULL,
	void_reff text NULL,
	sett_stmt_id text NULL,
	term_narr text NULL,
	trans_reff text NULL,
	prk_limit_id text NULL,
	skn_otdb_dr_chq text NULL,
	cheq_type text NULL,
	cheque_number text NULL,
	skn_trx_type text NULL,
	skn_snd_clrg_cd text NULL,
	skn_sender_name text NULL,
	skn_otcr_bnk_cd text NULL,
	skn_otcr_ben_nm text NULL,
	skn_otdb_bnk_cd text NULL,
	rtgs_ben_mem_cd text NULL,
	rtgs_ben_ult_nm text NULL,
	rtgs_sen_ori_nm text NULL,
	rtgs_data_id text NULL,
	bil_product text NULL,
	bil_customer text NULL,
	dr_narrative text NULL,
	cr_narrative text NULL,
	l_va_number text NULL,
	skn_otcr_ben_ac text NULL,
	skn_otcr_remark text NULL,
	rtgs_ben_mem_ac text NULL,
	rtgs_ben_mem_nm text NULL,
	rtgs_ben_ult_ac text NULL,
	rtgs_remark text NULL,
	l_va_type text NULL,
	l_va_name text NULL,
	send_acct_deft text NULL,
	skn_otdb_dr_acc text NULL,
	ben_name text NULL,
	in_send_corr_bk text NULL,
	ord_cust_acct text NULL,
	in_ordering_cus text NULL,
	skn_otcr_ben_ad text NULL,
	va_sender_name text NULL
);


-- landing_dq.bss_kyc_sumber_dana definition

-- Drop table

-- DROP TABLE landing_dq.bss_kyc_sumber_dana;

CREATE TABLE landing_dq.bss_kyc_sumber_dana (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	sumber_dana_id text NULL,
	description text NULL,
	reserved_3 text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_lbu_sektor_economy definition

-- Drop table

-- DROP TABLE landing_dq.bss_lbu_sektor_economy;

CREATE TABLE landing_dq.bss_lbu_sektor_economy (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	code text NULL,
	description text NULL,
	reserved_3 text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_ld definition

-- Drop table

-- DROP TABLE landing_dq.bss_ld;

CREATE TABLE landing_dq.bss_ld (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	sector text NULL,
	customer_id text NULL,
	currency text NULL,
	value_date text NULL,
	limit_reference text NULL,
	category text NULL,
	int_rate_type text NULL,
	interest_rate text NULL,
	position_type text NULL,
	portfolio_no text NULL,
	overdue_status text NULL,
	customer_no text NULL,
	asset_class text NULL,
	alt_ld_id text NULL,
	lbu_pfolio text NULL,
	amount text NULL,
	sid_kat_deb text NULL,
	lbu_or_guna text NULL,
	kyc_jenis_peng text NULL,
	sid_sektor_econ text NULL,
	sid_lokasi_pryk text NULL,
	gur_name text NULL,
	jenis_penjamin text NULL,
	gur_gol_penjami text NULL,
	gur_bagian_dija text NULL,
	gur_legal_id text NULL,
	gur_npwp text NULL,
	gur_street text NULL,
	lbu_sektor_eko text NULL,
	or_guna text NULL,
	lbu_kat_ukur text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	lbu_sifat_kred text NULL,
	sid_sifat_kredi text NULL,
	ld_flat_rate text NULL,
	sub_product text NULL,
	status text NULL,
	fin_mat_date text NULL,
	orig_val_date text NULL,
	ld_pk_number text NULL,
	amount_increase text NULL,
	amt_v_date text NULL,
	ld_sub_product text NULL,
	rpt_f_int_float text NULL,
	currency_market text NULL,
	bus_day_defn text NULL,
	third_party_ref text NULL,
	customer_ref text NULL,
	drawdown_account text NULL,
	interest_basis text NULL,
	int_paymt_method text NULL,
	interest_key text NULL,
	interest_spread text NULL,
	accrual_param text NULL,
	int_ref_number text NULL,
	mis_interest_key text NULL,
	mis_interest_rate text NULL,
	capitalisation text NULL,
	tot_interest_amt text NULL,
	int_start_date text NULL,
	int_end_date text NULL,
	band_level_ind text NULL,
	tax_principal_key text NULL,
	tax_int_key text NULL,
	tax_commission_key text NULL,
	w_h_tax_alt text NULL,
	w_h_tax_rate_key text NULL,
	liquidation_code text NULL,
	comm_calc_method text NULL,
	comm_paymt_method text NULL,
	comm_rate text NULL,
	total_comm_amount text NULL,
	chrg_code text NULL,
	chrg_amount text NULL,
	chrg_claim_date text NULL,
	chrg_booked_on text NULL,
	chrg_capitalise text NULL,
	total_cap_charge text NULL,
	liquidation_mode text NULL,
	grace_period text NULL,
	grace_amount text NULL,
	penalty_key text NULL,
	penalty_spread text NULL,
	mis_funding_dept text NULL,
	use_def_pi_rate text NULL,
	neg_ref_number text NULL,
	princ_fx_rate text NULL,
	v_date_for_p_fx text NULL,
	trade_date text NULL,
	other_neg_ref text NULL,
	other_fx_rate text NULL,
	v_date_other_fx text NULL,
	paying_agent text NULL,
	max_contract_rate text NULL,
	min_contract_rate text NULL,
	accrual_rate text NULL,
	reduced_rate text NULL,
	delivery_link text NULL,
	walk_in_cust text NULL,
	prin_liq_acct text NULL,
	prin_ben_bank_1 text NULL,
	prin_ben_bank_2 text NULL,
	prin_address text NULL,
	benef_prin_acct text NULL,
	int_liq_acct text NULL,
	int_ben_bank_1 text NULL,
	int_ben_bank_2 text NULL,
	int_address text NULL,
	ben_int_acct text NULL,
	com_liq_acct text NULL,
	chrg_liq_acct text NULL,
	mis_acct_officer text NULL,
	federal_funds text NULL,
	clean_risk text NULL,
	reserves text NULL,
	secured__y_n text NULL,
	agreement_date text NULL,
	cross_ref_no text NULL,
	country_risk text NULL,
	country_exposure text NULL,
	central_bank_code text NULL,
	status_control text NULL,
	commitment_no text NULL,
	l_c_u_type text NULL,
	sta_y_n text NULL,
	l_c_u_conversion text NULL,
	l_c_u_calc_base text NULL,
	commt_avail_amt text NULL,
	tranche_amt text NULL,
	d_d_start_date text NULL,
	d_d_end_date text NULL,
	d_d_mult_amt text NULL,
	drawdown_issue_prc text NULL,
	dd_fee_code text NULL,
	dd_fee_amt text NULL,
	drawdown_net_amt text NULL,
	vd_date_adjustment text NULL,
	issue_pl_amount text NULL,
	vd_prior_adjust text NULL,
	participant_no text NULL,
	commit_drawing text NULL,
	issue_price text NULL,
	issue_accrual text NULL,
	reimburse_price text NULL,
	reimburse_amount text NULL,
	reimburse_pl_amt text NULL,
	reimburse_accrual text NULL,
	reimb_reserved text NULL,
	princ_dis_acct text NULL,
	com_reserve_1 text NULL,
	com_reserve_2 text NULL,
	com_reserve_3 text NULL,
	com_reserve_4 text NULL,
	com_reserve_5 text NULL,
	fee_pay_account text NULL,
	fee_reserve1 text NULL,
	fee_reserve2 text NULL,
	fee_reserve3 text NULL,
	fee_reserve4 text NULL,
	new_int_rate text NULL,
	new_spread text NULL,
	spread_v_date text NULL,
	drawdown_ent_date text NULL,
	cancellation_date text NULL,
	new_com_rate text NULL,
	com_rate_v_date text NULL,
	bk_to_bk_info text NULL,
	link_reference text NULL,
	cancelled_int text NULL,
	tot_cancel_int_amt text NULL,
	cust_remarks text NULL,
	alone_merge_ind text NULL,
	our_remarks text NULL,
	auto_scheds text NULL,
	define_scheds text NULL,
	contract_type text NULL,
	interest_due_date text NULL,
	comm_due_date text NULL,
	int_revision_date text NULL,
	margin_rev_date text NULL,
	activity text NULL,
	adv_sent text NULL,
	tot_int_tax text NULL,
	total_w_h_t text NULL,
	tot_com_tax text NULL,
	tot_princ_tax text NULL,
	send_payment text NULL,
	send_confirmation text NULL,
	note_denom text NULL,
	note_quantity text NULL,
	broker_code text NULL,
	brokerage text NULL,
	broker_ccy text NULL,
	broker_amount text NULL,
	linked_tfdr_ref text NULL,
	tran_type text NULL,
	version_used text NULL,
	ld_preclose_dt text NULL,
	ld_restruct_dt text NULL,
	ld_orimat_dt text NULL,
	ld_acct_officer text NULL,
	ld_int_diff text NULL,
	dt_chg_ass_cls text NULL,
	l_ld_restru_flg text NULL,
	l_ld_restru_ln text NULL,
	lbu_jenis_peng text NULL,
	sid_jenis_peng text NULL,
	gur_city text NULL,
	gur_zip_code text NULL,
	gur_province text NULL,
	gur_dati2 text NULL,
	ld_sandi_kond text NULL,
	dm_original_amt text NULL,
	alt_limit_id text NULL,
	nil_proyek_bi text NULL,
	amt_legacy_mig text NULL,
	ld_extra_info text NULL,
	linked_tflc_ref text NULL,
	last_version text NULL,
	otor_version text NULL,
	joint_holder text NULL,
	relation_code text NULL,
	joint_notes text NULL,
	annuity_pay_method text NULL,
	residual_value text NULL,
	annuity_repay_amt text NULL,
	bill_txn_amount text NULL,
	tax_principal_type text NULL,
	tax_int_type text NULL,
	tax_commissn_type text NULL,
	contract_grp text NULL,
	bill_number text NULL,
	bill_redisc_rate text NULL,
	prin_inc_limamt text NULL,
	inclusive_csn text NULL,
	csn_calc_type text NULL,
	asset_reference text NULL,
	fin_chg_calc_type text NULL,
	days_pre_advice text NULL,
	fv_rate_key text NULL,
	fv_margin_key text NULL,
	int_tax_lcy text NULL,
	net_int_tax_lcy text NULL,
	int_tax_fcy text NULL,
	net_int_tax_fcy text NULL,
	return_int text NULL,
	return_com text NULL,
	ld_reserved text NULL,
	hb_curr_period text NULL,
	yield_method text NULL,
	mat_amount text NULL,
	flat_comm_type text NULL,
	mature_at_sod text NULL,
	matured_online text NULL,
	currency_code text NULL,
	excg_rate text NULL,
	settlement_market text NULL,
	conversion_type text NULL,
	rev_contingent text NULL,
	last_day_accrual text NULL,
	defaulted_value text NULL,
	fwd_bwd_key text NULL,
	base_date_key text NULL,
	mis_cof_type text NULL,
	mis_cof_rate text NULL,
	mis_cof_dept text NULL,
	red_recourse text NULL,
	third_party_id text NULL,
	third_lim_ref text NULL,
	dealer_desk text NULL,
	negative_rate text NULL,
	penalty_rate text NULL,
	int_coll_method text NULL,
	provision text NULL,
	provision_amount text NULL,
	provision_method text NULL,
	repay_cap text NULL,
	fwd_proj text NULL,
	rounding_rule text NULL,
	commt_reinitiate text NULL,
	curr_pd_pr_amt text NULL,
	online_eff_date text NULL,
	online_rpy_type text NULL,
	online_rpy_amt text NULL,
	ias_classification text NULL,
	ias_subtype text NULL,
	market_key text NULL,
	market_margin text NULL,
	special_int_basis text NULL,
	special_comm_basis text NULL,
	compound_type text NULL,
	compound_yield_method text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	stmt_no text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	orig_int_rate text NULL,
	oth_ac_officer text NULL,
	annuity_st_date text NULL,
	l_ast_sell_flag text NULL,
	l_asset_sell_id text NULL,
	l_ast_sell_date text NULL,
	l_ast_sell_link text NULL,
	bank_portion text NULL,
	ld_fos text NULL,
	manual_pro_date text NULL,
	referal_id text NULL,
	int_rate_v_date text NULL,
	ld_reg_flag text NULL,
	orig_val_t24 text NULL,
	orig_int_t24 text NULL,
	dm_original_t24 text NULL,
	dm_int_spread text NULL,
	dm_interest_key text NULL
);


-- landing_dq.bss_ld_sub_product definition

-- Drop table

-- DROP TABLE landing_dq.bss_ld_sub_product;

CREATE TABLE landing_dq.bss_ld_sub_product (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	description text NULL,
	ld_categ text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_limit definition

-- Drop table

-- DROP TABLE landing_dq.bss_limit;

CREATE TABLE landing_dq.bss_limit (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	limit_currency text NULL,
	approval_date text NULL,
	expiry_date text NULL,
	online_limit_date text NULL,
	internal_amount text NULL,
	collateral_code text NULL,
	online_limit text NULL,
	commitm_amt text NULL,
	account text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	tgl_pk_awal text NULL,
	tgl_pk_akhir text NULL,
	no_pk_limit text NULL,
	no_pk_limend text NULL,
	product_allowed text NULL,
	co_book text NULL,
	record_parent text NULL,
	dt_old_exp text NULL,
	dt_upd_limit text NULL,
	lbu_jn_guna text NULL,
	avail_amt text NULL,
	committed_flag text NULL,
	reducing_limit text NULL,
	gur_name text NULL,
	jenis_penjamin text NULL,
	gur_gol_penjami text NULL,
	gur_bagian_dija text NULL,
	gur_legal_id text NULL,
	gur_npwp text NULL,
	gur_street text NULL,
	collat_right text NULL,
	group_db text NULL,
	limit_product text NULL,
	lbu_pfolio text NULL,
	sid_kat_deb text NULL,
	lbu_sifat_kred text NULL,
	lbu_sektor_eko text NULL,
	lbu_kat_ukur text NULL,
	lbu_jenis_peng text NULL,
	lbu_or_guna text NULL,
	lb_jenis_kredit text NULL,
	sid_sifat_kredi text NULL,
	sid_jenis_peng text NULL,
	sid_sektor_econ text NULL,
	nil_proyek_bi text NULL,
	sid_lokasi_pryk text NULL,
	alt_limit_id text NULL,
	record_status text NULL,
	total_os text NULL,
	country_of_risk text NULL,
	country_percent text NULL,
	offered_until text NULL,
	review_frequency text NULL,
	adm_extension_date text NULL,
	proposal_date text NULL,
	limit_grade text NULL,
	grade_percent text NULL,
	notes text NULL,
	advised_amount text NULL,
	fixed_variable text NULL,
	coll_reqd_amt text NULL,
	coll_reqd_prcnt text NULL,
	up_to_period text NULL,
	period_amt text NULL,
	period_prcnt text NULL,
	maximum_secured text NULL,
	maximum_unsecured text NULL,
	maximum_total text NULL,
	other_secured text NULL,
	secured_amt text NULL,
	time_code text NULL,
	limit_band text NULL,
	sub_alloc_taken text NULL,
	sub_alloc_given text NULL,
	commt_amt_avail text NULL,
	s_al_tkn_ccy text NULL,
	s_al_tkn_amt text NULL,
	s_al_gvn_ccy text NULL,
	s_al_gvn_amt text NULL,
	commitm_ccy text NULL,
	os_ccy text NULL,
	os_amt text NULL,
	date_of_excess text NULL,
	amt_last_excess text NULL,
	date_last_moved text NULL,
	amt_last_moved text NULL,
	date_1st_excess text NULL,
	date_last_reval text NULL,
	original_limit text NULL,
	clean_risk text NULL,
	date_clrisk_exc text NULL,
	available_marker text NULL,
	allowed_cust text NULL,
	restricted_cust text NULL,
	allowed_ccy text NULL,
	allowed_amt text NULL,
	restricted_ccy text NULL,
	allowed_comp text NULL,
	restricted_comp text NULL,
	commodity text NULL,
	commodity_pcent text NULL,
	collat_code text NULL,
	collat_customer text NULL,
	collat_ccy text NULL,
	collat_amount text NULL,
	collat_percent text NULL,
	collat_location text NULL,
	collat_grade text NULL,
	collat_notes text NULL,
	reducing_sched text NULL,
	repay_freq text NULL,
	repay_number text NULL,
	repay_ccy text NULL,
	repay_amount text NULL,
	repay_end_date text NULL,
	repay_notes text NULL,
	acc_company text NULL,
	no_of_sub_allocs text NULL,
	fx_or_time_band text NULL,
	liability_number text NULL,
	credit_line text NULL,
	check_limit text NULL,
	consol_key text NULL,
	allow_netting text NULL,
	dispo_officer text NULL,
	online_update text NULL,
	increasing_type text NULL,
	increase_freq text NULL,
	increase_ccy text NULL,
	increase_amount text NULL,
	incr_end_date text NULL,
	gur_city text NULL,
	gur_street2 text NULL,
	gur_zip_code text NULL,
	gur_street3 text NULL,
	gur_province text NULL,
	reserved1 text NULL,
	reserved2 text NULL,
	reserved3 text NULL,
	reserved4 text NULL,
	charge_code text NULL,
	charge_amount text NULL,
	admin_fee_code text NULL,
	admin_fee_chrg text NULL,
	prk_chrg_acct text NULL,
	or_guna text NULL,
	unutil_acct text NULL,
	curr_unutil_amt text NULL,
	allow_unutil_cr text NULL,
	prev_unutil_acct text NULL,
	prev_unutil_amt text NULL,
	last_draw_date text NULL,
	created_from text NULL,
	limits_modified text NULL,
	util_account text NULL,
	curr_util_amt text NULL,
	prev_util_acct text NULL,
	prev_util_amt text NULL,
	alloc_work_id text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	override text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	l_tgl_macet text NULL,
	l_sid_sbmct text NULL,
	l_ket_macet text NULL,
	l_tgl_res text NULL,
	l_no_res text NULL,
	l_tgl_res_awal text NULL,
	l_limit_order text NULL,
	l_tgl_loan text NULL,
	l_cara_restr text NULL,
	take_over text NULL,
	orig_exp_date text NULL,
	orig_appr_date text NULL
);


-- landing_dq.bss_md_deal definition

-- Drop table

-- DROP TABLE landing_dq.bss_md_deal;

CREATE TABLE landing_dq.bss_md_deal (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	deal_no text NULL,
	customer text NULL,
	currency text NULL,
	value_date text NULL,
	maturity_date text NULL,
	deal_sub_type text NULL,
	category text NULL,
	limit_reference text NULL,
	principal_amount text NULL,
	benef_cust_2 text NULL,
	outs_prov_amt text NULL,
	country_risk text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	deal_date text NULL,
	alternate_id text NULL,
	ben_address text NULL,
	lbu_pfolio text NULL
);


-- landing_dq.bss_pd definition

-- Drop table

-- DROP TABLE landing_dq.bss_pd;

CREATE TABLE landing_dq.bss_pd (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	customer text NULL,
	currency text NULL,
	position_type text NULL,
	category text NULL,
	limit_reference text NULL,
	tot_ovrdue_type text NULL,
	tot_od_type_amt text NULL,
	portfolio_number text NULL,
	status text NULL,
	ld_hb_dt text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	pay_amt_outs text NULL,
	payment_dte_due text NULL,
	asset_class text NULL,
	pay_type text NULL,
	outstanding_amt text NULL,
	currency_market text NULL,
	dealer_desk text NULL,
	account_officer text NULL,
	interest_basis text NULL,
	orig_stlmnt_act text NULL,
	parameter_record text NULL,
	orig_limit_ref text NULL,
	limit_amount text NULL,
	total_amt_to_repay text NULL,
	final_due_date text NULL,
	repayment_acct text NULL,
	last_version text NULL,
	start_date text NULL,
	loan_spread text NULL,
	provision text NULL,
	provision_amount text NULL,
	provision_method text NULL,
	stmt_no text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	manual_pro_date text NULL,
	payment_amount text NULL,
	adjusted_amt text NULL,
	new_outs_amt text NULL,
	tot_repay_amt text NULL,
	repayment_date text NULL,
	move_to_his text NULL
);


-- landing_dq.bss_pd_payment_due definition

-- Drop table

-- DROP TABLE landing_dq.bss_pd_payment_due;

CREATE TABLE landing_dq.bss_pd_payment_due (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	customer text NULL,
	currency text NULL,
	position_type text NULL,
	category text NULL,
	limit_reference text NULL,
	tot_ovrdue_type text NULL,
	tot_od_type_amt text NULL,
	portfolio_number text NULL,
	status text NULL,
	ld_hb_dt text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	pay_amt_outs text NULL,
	payment_dte_due text NULL,
	asset_class text NULL,
	pay_type text NULL,
	outstanding_amt text NULL
);


-- landing_dq.bss_re_consol_spec_entry definition

-- Drop table

-- DROP TABLE landing_dq.bss_re_consol_spec_entry;

CREATE TABLE landing_dq.bss_re_consol_spec_entry (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_number text NULL,
	company_code text NULL,
	amount_fcy text NULL,
	amount_lcy text NULL,
	transaction_code text NULL,
	their_reference text NULL,
	pl_category text NULL,
	customer_id text NULL,
	exchange_rate text NULL,
	exposure_date text NULL,
	currency_market text NULL,
	local_ref text NULL,
	system_id text NULL,
	stmt_no text NULL,
	record_status text NULL,
	inputter text NULL,
	booking_date text NULL,
	value_date text NULL,
	consol_key text NULL,
	accounting_date text NULL,
	trade_date text NULL,
	our_reference text NULL,
	currency text NULL,
	account_officer text NULL,
	product_category text NULL,
	trans_reference text NULL,
	authoriser text NULL,
	date_time text NULL,
	reversal_marker text NULL,
	processing_date text NULL,
	narrative text NULL,
	master_account text NULL
);


-- landing_dq.bss_re_stat_line_bal definition

-- Drop table

-- DROP TABLE landing_dq.bss_re_stat_line_bal;

CREATE TABLE landing_dq.bss_re_stat_line_bal (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	line_ccy_date text NULL,
	open_bal text NULL,
	open_bal_lcl text NULL,
	cr_movement text NULL,
	cr_mvmt_lcl text NULL,
	db_movement text NULL,
	db_mvmt_lcl text NULL,
	closing_bal text NULL,
	closing_bal_lcl text NULL,
	report_name text NULL,
	report_line text NULL,
	currency text NULL,
	system_date text NULL,
	line_name text NULL
);


-- landing_dq.bss_re_stat_rep_line definition

-- Drop table

-- DROP TABLE landing_dq.bss_re_stat_rep_line;

CREATE TABLE landing_dq.bss_re_stat_rep_line (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	rep_name_line_no text NULL,
	total_print text NULL,
	total_accum text NULL,
	k_type text NULL,
	descr text NULL,
	asset_applic_id text NULL,
	asset_type text NULL,
	"type" text NULL,
	asset_ccy_mkt text NULL,
	asset_pos_type text NULL,
	asset_currency text NULL,
	curr_no text NULL,
	inputter text NULL,
	authoriser text NULL,
	co_code text NULL,
	line_balance text NULL,
	date_time text NULL,
	asset1 text NULL,
	asset2 text NULL,
	asset3 text NULL,
	asset4 text NULL,
	asset5 text NULL,
	asset6 text NULL,
	asset7 text NULL,
	asset8 text NULL,
	asset_ext_dup text NULL,
	proft_applic_id text NULL,
	profit1 text NULL,
	profit2 text NULL,
	profit3 text NULL,
	profit4 text NULL,
	profit5 text NULL,
	profit6 text NULL,
	profit7 text NULL,
	profit8 text NULL,
	proft_currency text NULL,
	proft_ext_dup text NULL
);


-- landing_dq.bss_repo definition

-- Drop table

-- DROP TABLE landing_dq.bss_repo;

CREATE TABLE landing_dq.bss_repo (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	currency text NULL,
	value_date text NULL,
	maturity_date text NULL,
	new_nominal text NULL,
	principal_amount_1 text NULL,
	repo_rate text NULL,
	repo_type text NULL,
	new_sec_code text NULL,
	counterparty text NULL,
	bank_portfolio text NULL,
	limit_reference text NULL,
	principal_amount_2 text NULL,
	interest_amount text NULL,
	contract_status text NULL,
	gross_amt_sec text NULL,
	repo_interest text NULL
);


-- landing_dq.bss_sc_trading_position definition

-- Drop table

-- DROP TABLE landing_dq.bss_sc_trading_position;

CREATE TABLE landing_dq.bss_sc_trading_position (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	discount_accrued text NULL,
	current_position text NULL,
	disc_accr_posted text NULL,
	dealer_book text NULL,
	cur_avg_price text NULL,
	security_code text NULL,
	issuer text NULL,
	cur_cost_position text NULL,
	cpn_accr_posted text NULL
);


-- landing_dq.bss_sec_acc_master definition

-- Drop table

-- DROP TABLE landing_dq.bss_sec_acc_master;

CREATE TABLE landing_dq.bss_sec_acc_master (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	portfolio_type text NULL,
	customer_number text NULL,
	reference_currency text NULL,
	portfolio_turnover text NULL,
	start_date text NULL,
	closure_date text NULL,
	co_code text NULL,
	date_time text NULL,
	curr_no text NULL,
	portfolio_type_1 text NULL
);


-- landing_dq.bss_sec_trade definition

-- Drop table

-- DROP TABLE landing_dq.bss_sec_trade;

CREATE TABLE landing_dq.bss_sec_trade (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	cust_sec_acc text NULL,
	br_price text NULL,
	br_no_nom text NULL,
	security_code text NULL,
	interest_rate text NULL,
	cu_gross_am_sec text NULL,
	value_date text NULL,
	cust_tot_nom text NULL,
	trade_date text NULL,
	broker_no text NULL
);


-- landing_dq.bss_sector definition

-- Drop table

-- DROP TABLE landing_dq.bss_sector;

CREATE TABLE landing_dq.bss_sector (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	description text NULL,
	curr_no text NULL,
	co_code text NULL,
	date_time text NULL
);


-- landing_dq.bss_security_master definition

-- Drop table

-- DROP TABLE landing_dq.bss_security_master;

CREATE TABLE landing_dq.bss_security_master (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	sub_asset_type text NULL,
	call_put_ind text NULL,
	security_currency text NULL,
	rating text NULL,
	security_domicile text NULL,
	issue_date text NULL,
	maturity_date text NULL,
	interest_rate text NULL,
	issuer text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	company_name text NULL,
	short_name text NULL,
	sandi_bi text NULL,
	sc_portfolio text NULL,
	sc_lembaga_rank text NULL,
	sc_date_rank text NULL,
	sc_gol_penerbit text NULL,
	i_s_i_n text NULL
);


-- landing_dq.bss_security_position definition

-- Drop table

-- DROP TABLE landing_dq.bss_security_position;

CREATE TABLE landing_dq.bss_security_position (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	security_account text NULL,
	security_number text NULL,
	closing_bal_no_nom text NULL,
	cost_invst_sec_ccy text NULL,
	income_curr_period text NULL
);


-- landing_dq.bss_stmt_entry definition

-- Drop table

-- DROP TABLE landing_dq.bss_stmt_entry;

CREATE TABLE landing_dq.bss_stmt_entry (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_number text NULL,
	company_code text NULL,
	amount_fcy text NULL,
	amount_lcy text NULL,
	transaction_code text NULL,
	their_reference text NULL,
	pl_category text NULL,
	customer_id text NULL,
	exchange_rate text NULL,
	exposure_date text NULL,
	currency_market text NULL,
	local_ref text NULL,
	system_id text NULL,
	stmt_no text NULL,
	record_status text NULL,
	inputter text NULL,
	booking_date text NULL,
	value_date text NULL,
	consol_key text NULL,
	accounting_date text NULL,
	trade_date text NULL,
	our_reference text NULL,
	currency text NULL,
	account_officer text NULL,
	product_category text NULL,
	trans_reference text NULL,
	authoriser text NULL,
	date_time text NULL,
	reversal_marker text NULL,
	processing_date text NULL,
	narrative text NULL,
	master_account text NULL,
	repayment_type text NULL,
	repayment_amt text NULL,
	net_param text NULL
);


-- landing_dq.bss_stmt_entry_detail definition

-- Drop table

-- DROP TABLE landing_dq.bss_stmt_entry_detail;

CREATE TABLE landing_dq.bss_stmt_entry_detail (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	account_number text NULL,
	company_code text NULL,
	amount_fcy text NULL,
	amount_lcy text NULL,
	transaction_code text NULL,
	their_reference text NULL,
	pl_category text NULL,
	customer_id text NULL,
	exchange_rate text NULL,
	exposure_date text NULL,
	currency_market text NULL,
	local_ref text NULL,
	system_id text NULL,
	stmt_no text NULL,
	record_status text NULL,
	inputter text NULL,
	booking_date text NULL,
	value_date text NULL,
	consol_key text NULL,
	accounting_date text NULL,
	trade_date text NULL,
	our_reference text NULL,
	currency text NULL,
	account_officer text NULL,
	product_category text NULL,
	trans_reference text NULL,
	authoriser text NULL,
	date_time text NULL,
	reversal_marker text NULL,
	processing_date text NULL,
	narrative text NULL,
	master_account text NULL,
	repayment_type text NULL,
	repayment_amt text NULL,
	net_param text NULL
);


-- landing_dq.bss_teller_transaction definition

-- Drop table

-- DROP TABLE landing_dq.bss_teller_transaction;

CREATE TABLE landing_dq.bss_teller_transaction (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	teller_transaction text NULL,
	short_desc text NULL,
	transaction_code_1 text NULL,
	cat_dept_code_1 text NULL,
	valid_currencies_1 text NULL,
	valid_accounts_1 text NULL,
	curr_mkt_1 text NULL,
	pos_type_1 text NULL,
	reserve_2 text NULL,
	transaction_code_2 text NULL,
	cat_dept_code_2 text NULL,
	valid_currencies_2 text NULL,
	valid_accounts_2 text NULL,
	curr_mkt_2 text NULL,
	pos_type_2 text NULL,
	deal_market text NULL,
	charge_market text NULL,
	print_advice text NULL,
	advice_version text NULL,
	teller_transfer text NULL,
	cust_ac_transfer text NULL,
	verify_signature text NULL,
	charge_code text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	k_desc text NULL,
	validate_sort_code text NULL,
	"desc" text NULL,
	split_chrg_entries text NULL,
	defer_charges text NULL,
	local_ref text NULL,
	auto_denominate text NULL,
	denom_filter text NULL,
	cr_denom_type text NULL,
	dr_denom_type text NULL,
	res_9 text NULL,
	res_8 text NULL,
	res_7 text NULL,
	res_6 text NULL,
	res_5 text NULL,
	res_4 text NULL,
	res_3 text NULL,
	res_2 text NULL,
	res_1 text NULL,
	chg_type text NULL,
	txn_type text NULL
);


-- landing_dq.bss_transaction definition

-- Drop table

-- DROP TABLE landing_dq.bss_transaction;

CREATE TABLE landing_dq.bss_transaction (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	id text NULL,
	narrative text NULL,
	data_capture text NULL,
	cheque_ind text NULL,
	mandatory_ref_no text NULL,
	debit_credit_ind text NULL,
	charge_key text NULL,
	immediate_charge text NULL,
	default_value_date text NULL,
	exposure_date text NULL,
	turnover_charge text NULL,
	swift_narrative text NULL,
	unit_cost text NULL,
	initiation text NULL,
	short_desc text NULL,
	stmt_narr text NULL,
	stmt_narr_ref text NULL,
	force_def_exp_date text NULL,
	narr_type text NULL,
	txn_type text NULL,
	combine_prod_cat text NULL,
	combine_system_id text NULL,
	combine_txn text NULL,
	exp_key text NULL,
	chq_type text NULL,
	update_int_pools text NULL,
	dispo_exempt text NULL,
	reserved_7 text NULL,
	reserved_6 text NULL,
	reserved_5 text NULL,
	reserved_4 text NULL,
	reserved_3 text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	co_code text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.bss_transaction_teller definition

-- Drop table

-- DROP TABLE landing_dq.bss_transaction_teller;

CREATE TABLE landing_dq.bss_transaction_teller (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'BSS'::text,
	teller_id text NULL,
	debit_ref text NULL,
	credit_ref text NULL,
	teller_transaction_code text NULL,
	teller_id_1 text NULL,
	teller_id_2 text NULL,
	account_1 text NULL,
	customer_1 text NULL,
	account_2 text NULL,
	customer_2 text NULL,
	amount text NULL,
	value_date text NULL,
	cheq_type text NULL,
	cheque_number text NULL,
	recipt_no text NULL
);


-- landing_dq.coba_test definition

-- Drop table

-- DROP TABLE landing_dq.coba_test;

CREATE TABLE landing_dq.coba_test (
	id_seq bigserial NOT NULL,
	hmm varchar(50) NULL
);


-- landing_dq.ssab_coll_account definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_account;

CREATE TABLE landing_dq.ssab_coll_account (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	online_cleared_bal text NULL,
	locked_amount text NULL,
	inactiv_marker text NULL,
	co_code text NULL,
	customer_no text NULL,
	co_name text NULL,
	online_actual_bal text NULL,
	mud_nisbah text NULL,
	account_officer text NULL,
	account_officer_name text NULL,
	date_last_cr_cust text NULL,
	date_last_cr_bank text NULL,
	date_last_dr_cust text NULL,
	date_last_dr_bank text NULL,
	category text NULL,
	opening_date text NULL,
	closure_date text NULL,
	passbook_id text NULL,
	mud_nisbah_1 text NULL,
	mud_nisbah_bank text NULL,
	nisbah_eq_rate text NULL,
	l_ins_company text NULL,
	l_month_premium text NULL,
	zakat text NULL,
	condition_group text NULL,
	alt_acct_id text NULL,
	alt_dep_acct_id text NULL,
	account_title_1 text NULL,
	short_title text NULL,
	currency text NULL,
	passbook text NULL,
	referral_code text NULL,
	bonus_ps_rcv text NULL,
	joint_holder text NULL,
	relation_code text NULL,
	l_ins_nominee text NULL,
	l_ins_claim_amt text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL
);


-- landing_dq.ssab_coll_az_account definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_az_account;

CREATE TABLE landing_dq.ssab_coll_az_account (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	customer_id text NULL,
	currency text NULL,
	all_in_one_product text NULL,
	principal text NULL,
	value_date text NULL,
	maturity_date text NULL,
	repay_account text NULL,
	nominated_account text NULL,
	repayment_type text NULL,
	calculation_base text NULL,
	interest_rate text NULL,
	maturity_instr text NULL,
	roll_int_cap_fqu text NULL,
	roll_int_pay_fqu text NULL,
	cap_int_at_sod text NULL,
	type_of_schdle text NULL,
	amount text NULL,
	frequency text NULL,
	category_desc text NULL,
	lgcy_value_da text NULL,
	rollover_term text NULL,
	alt_az_acct_id text NULL
);


-- landing_dq.ssab_coll_category definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_category;

CREATE TABLE landing_dq.ssab_coll_category (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	description text NULL,
	short_name text NULL,
	system_ind text NULL,
	position_type text NULL
);


-- landing_dq.ssab_coll_collateral definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_collateral;

CREATE TABLE landing_dq.ssab_coll_collateral (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	manufacturer text NULL,
	vehicle_model text NULL,
	coll_certnum text NULL,
	dt_legal_date text NULL,
	address text NULL,
	coll_city text NULL,
	coll_ownernm text NULL,
	engine_number text NULL,
	chassis_number text NULL,
	manufacture_yr text NULL,
	coll_cond text NULL,
	vehicle_colour text NULL,
	police_num text NULL,
	coll_jns_peng text NULL,
	coll_id_agunan text NULL,
	coll_peringkat text NULL,
	nominal_value text NULL,
	coll_province text NULL,
	imb_num text NULL,
	land_size text NULL,
	build_size text NULL,
	legal_type text NULL,
	track_name text NULL,
	coll_dati2 text NULL,
	coll_penilai_in text NULL,
	col_no_bpkb text NULL,
	collateral_type text NULL,
	value_date text NULL,
	expiry_date text NULL,
	notes text NULL,
	execution_value text NULL,
	revalued_date text NULL,
	application text NULL,
	application_id text NULL,
	description text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	coll_address text NULL,
	lbu_penerbit text NULL,
	lbu_rating_date text NULL,
	lbu_rating_lmbg text NULL,
	l_sifat_agunan text NULL,
	last_version text NULL,
	otor_version text NULL,
	col_nil_njop text NULL,
	col_tgl_nil text NULL,
	appraisal_nm text NULL,
	appraisal_dt text NULL,
	appraisal_typ text NULL,
	alt_coll_id text NULL,
	collateral_code text NULL,
	co_code text NULL
);


-- landing_dq.ssab_coll_collateral_right definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_collateral_right;

CREATE TABLE landing_dq.ssab_coll_collateral_right (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	limit_reference text NULL,
	collateral_code text NULL,
	limit_ref_cust text NULL,
	customer text NULL,
	validity_date text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	percent_alloc text NULL
);


-- landing_dq.ssab_coll_customer2 definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_customer2;

CREATE TABLE landing_dq.ssab_coll_customer2 (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	sid_din text NULL,
	sector text NULL,
	company_book text NULL,
	name_1 text NULL,
	legal_holder_name text NULL,
	title text NULL,
	street text NULL,
	ktp_rt text NULL,
	ktp_rw text NULL,
	ktp_kelurahan text NULL,
	ktp_kacamatan text NULL,
	town_country text NULL,
	ktp_provinsi text NULL,
	post_code text NULL,
	sid_dati2_debtor text NULL,
	legal_doc_name text NULL,
	legal_id text NULL,
	legal_exp_date text NULL,
	gender text NULL,
	marital_status text NULL,
	date_of_birth text NULL,
	place_of_birth text NULL,
	employment_start text NULL,
	employment_status text NULL,
	last_education text NULL,
	sid_sektor_econ text NULL,
	sid_golongan_de text NULL,
	mother_maid_nam text NULL,
	cus_npwp text NULL,
	residence_status text NULL,
	residence_since text NULL,
	phone_1 text NULL,
	sms_1 text NULL,
	no_of_dependents text NULL,
	net_monthly_in text NULL,
	net_monthly_out text NULL,
	home_street text NULL,
	home_rt text NULL,
	home_rw text NULL,
	home_kelurahan text NULL,
	home_kacamatan text NULL,
	hm_town_country text NULL,
	home_provinsi text NULL,
	home_post_code text NULL,
	spouse_name text NULL,
	spou_dt_of_birt text NULL,
	spou_pl_of_birt text NULL,
	spouse_id text NULL,
	con_relation text NULL,
	contact_person text NULL,
	con_address text NULL,
	con_phone text NULL,
	employers_name text NULL,
	off_street text NULL,
	off_town_city text NULL,
	off_post_code text NULL,
	off_phone text NULL,
	kyc_akte_no text NULL,
	sid_tgl_akte_ak text NULL,
	badan_hukum text NULL,
	peng_pemilikan text NULL,
	occupation text NULL,
	job_title text NULL,
	nationality text NULL,
	kyc_jenis_peng text NULL,
	sid_sifat_kredi text NULL,
	sid_gol_kredit text NULL,
	cus_open_date text NULL,
	legal_iss_date text NULL,
	occupation_desc text NULL,
	last_education_desc text NULL,
	industry text NULL,
	customer_code text NULL,
	given_names text NULL,
	family_name text NULL,
	name_2 text NULL,
	short_name text NULL,
	mnemonic text NULL,
	account_officer text NULL,
	other_officer text NULL,
	target text NULL,
	customer_status text NULL,
	residence text NULL,
	customer_rating text NULL,
	birth_incorp_date text NULL,
	company_type text NULL,
	"language" text NULL,
	religion text NULL,
	fdsl_cu_rsk_flg text NULL,
	country text NULL,
	ktp_coordinate text NULL,
	home_coordinate text NULL,
	mailing_address text NULL,
	email_1 text NULL,
	fax_1 text NULL,
	fax_1_1 text NULL,
	legal_iss_auth text NULL,
	relation_code text NULL,
	rel_customer text NULL,
	revers_rel_code text NULL,
	rel_deliv_opt text NULL,
	"role" text NULL,
	role_more_info text NULL,
	role_notes text NULL,
	customer_liability text NULL,
	previous_name text NULL,
	change_date text NULL,
	change_reason text NULL,
	customer_since text NULL,
	interests text NULL,
	other_nationality text NULL,
	domicile text NULL,
	spoken_language text NULL,
	further_details text NULL,
	pastimes text NULL,
	residence_type text NULL,
	residence_month text NULL,
	residence_year text NULL,
	residence_value text NULL,
	comm_type text NULL,
	pref_channel text NULL,
	confid_txt text NULL,
	contact_date text NULL,
	kyc_relationship text NULL,
	kyc_fund_src text NULL,
	kyc_income_src text NULL,
	kyc_sumber_dana text NULL,
	kyc_cash_dep_li text NULL,
	kyc_cash_dep_fq text NULL,
	kyc_cash_wd_lim text NULL,
	kyc_cash_wd_fq text NULL,
	kyc_noncash_lim text NULL,
	kyc_noncash_fq text NULL,
	kyc_non_cash_wd text NULL,
	kyc_noncash_fqu text NULL,
	kyc_busi_lic_no text NULL,
	kyc_revenue text NULL,
	kyc_cap_owner text NULL,
	comp_permit_no text NULL,
	company_bank text NULL,
	employers_add text NULL,
	employers_buss text NULL,
	customer_currency text NULL,
	salary text NULL,
	annual_bonus text NULL,
	salary_date_freq text NULL,
	fixed_allowance text NULL,
	other_income text NULL,
	kyc_incom_rng text NULL,
	kyc_intend_fund text NULL,
	kyc_purpose_acc text NULL,
	no_of_wife text NULL,
	no_of_child text NULL,
	no_of_parents text NULL,
	issue_cheques text NULL,
	tax_id text NULL,
	atm_number text NULL,
	fdsl_crd_number text NULL,
	inactive_cust text NULL,
	duplicate_cif text NULL,
	spouse_address text NULL,
	sid_group_id text NULL,
	sid_jenis_usaha text NULL,
	sid_malanggar text NULL,
	sid_melampaui text NULL,
	sid_rating_deb text NULL,
	sid_tempat_akte text NULL,
	sid_lembanga text NULL,
	parent_name text NULL,
	parent_dob text NULL,
	parent_birth_pl text NULL,
	sid_go_public text NULL,
	sid_kode_peng text NULL,
	loan_to_bank text NULL,
	gur_name text NULL,
	gur_legal_id text NULL,
	gur_npwp text NULL,
	gur_loan_no text NULL,
	gur_relation text NULL,
	gur_gol_penjami text NULL,
	gur_street text NULL,
	gur_addrs_rt text NULL,
	gur_addrs_rw text NULL,
	gur_kelurahan text NULL,
	gur_kecamatan text NULL,
	gur_city text NULL,
	gur_zip_code text NULL,
	gur_province text NULL,
	gur_bagian_dija text NULL,
	gur_prime_bank text NULL,
	gur_phone text NULL,
	gur_id text NULL,
	peng_id text NULL,
	peng_nama text NULL,
	peng_jenis_kela text NULL,
	peng_identitas text NULL,
	peng_npwp text NULL,
	peng_alamat text NULL,
	peng_dati2 text NULL,
	peng_kelurahan text NULL,
	peng_kecamatan text NULL,
	peng_id_jabatan text NULL,
	sid_id_debitur text NULL,
	sid_related text NULL,
	bank_name text NULL,
	type_of_loan text NULL,
	loan_value text NULL,
	alt_cust_id text NULL,
	sid_gelar text NULL,
	lbu_gol_deb text NULL,
	lbu_sandi_bank text NULL,
	lbu_status_deb text NULL,
	sid_gelar_1 text NULL,
	sid_hub_bank text NULL,
	sid_kat_deb text NULL,
	sid_kat_port text NULL,
	sid_pihak_kait text NULL,
	sid_rating_tgl text NULL,
	sid_dati2_lahir text NULL,
	alt_cus_id text NULL,
	l_no_of_dep text NULL,
	l_pisah_harta text NULL,
	co_code text NULL,
	ben_jenis_peng text NULL,
	ben_npwp text NULL,
	ben_legal_id text NULL,
	ben_ldoc_name text NULL,
	ben_nationality text NULL,
	address text NULL,
	sid_group_name text NULL,
	date_time text NULL,
	curr_no text NULL,
	ktp_addr_flag text NULL,
	customer_type text NULL,
	red_flag text NULL,
	off_provinsi text NULL,
	parent_customer text NULL,
	rel_to_parent text NULL,
	internet_banking_service text NULL,
	mobile_banking_service text NULL,
	override text NULL,
	record_status text NULL,
	inputter text NULL,
	authoriser text NULL,
	l_alamat_kor_fl text NULL,
	l_cus_shr_data text NULL,
	cus_anggota text NULL,
	ben_name text NULL,
	ben_jns_kelamin text NULL,
	ben_alamat text NULL,
	ben_kecamatan text NULL,
	ben_provinsi text NULL,
	ben_lahir_tmp text NULL,
	ben_sumber_dana text NULL,
	ben_status text NULL,
	ben_kelurahan text NULL,
	ben_kota text NULL,
	ben_kodepos text NULL,
	ben_handphone text NULL,
	ben_lahir_tgl text NULL,
	ben_in_rng_1 text NULL,
	l_jml_karyawan text NULL
);


-- landing_dq.ssab_coll_dept_acct_officer definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_dept_acct_officer;

CREATE TABLE landing_dq.ssab_coll_dept_acct_officer (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	area text NULL,
	"name" text NULL,
	delivery_point text NULL,
	dept_type text NULL
);


-- landing_dq.ssab_coll_ld_loans_and_deposits definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_ld_loans_and_deposits;

CREATE TABLE landing_dq.ssab_coll_ld_loans_and_deposits (
	business_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	amount text NULL,
	value_date text NULL,
	fin_mat_date text NULL,
	annuity_pay_method text NULL,
	interest_rate text NULL,
	annuity_repay_amt text NULL,
	fwl_pft_cap text NULL,
	dates text NULL,
	portfolio_type text NULL,
	customer_id text NULL,
	co_code text NULL,
	drawdown_net_amt text NULL,
	mis_acct_officer text NULL,
	mis_name text NULL,
	category text NULL,
	loan_type text NULL,
	ld_restruct_dt text NULL,
	l_ld_restru_flg text NULL,
	product_type text NULL,
	loan_type_desc text NULL,
	fwl_supp_paid text NULL,
	account_officer text NULL,
	ao_name text NULL,
	category_name text NULL,
	mb_profit_rate text NULL,
	l_mur_eff_rate text NULL,
	alt_ld_id text NULL,
	l_ld_restru_ln text NULL,
	mur_repay_freq text NULL,
	prin_liq_acct text NULL,
	int_liq_acct text NULL,
	tot_interest_amt text NULL,
	status text NULL,
	l_fos_id text NULL,
	inputter text NULL,
	authoriser text NULL,
	date_time text NULL,
	dm_original_amt text NULL,
	ld_pk_number text NULL,
	orig_val_date text NULL,
	asset_class text NULL,
	tenor text NULL,
	sid_sifat_kredit text NULL,
	sid_gol_kredit text NULL,
	l_sid_jns_peng text NULL,
	l_sid_ort_peng text NULL,
	sid_sektor_econ text NULL,
	sid_dati2debtor text NULL,
	int_fl text NULL,
	diskon_preclose text NULL,
	l_byr_preclose text NULL,
	l_os_preclose text NULL,
	l_diskon_margin text NULL,
	l_diskon_pokok text NULL,
	l_income_margin text NULL,
	l_biaya_margin text NULL,
	l_biaya_pokok text NULL,
	l_biaya text NULL,
	l_sisa_hari text NULL,
	l_unamort_adj text NULL,
	l_amt_v_date text NULL,
	l_grace_amount text NULL,
	l_collector_id text NULL,
	l_last_outs_ld text NULL,
	pd_id text NULL,
	overdue_status text NULL,
	flag_sell_bank text NULL,
	l_unamort_marg text NULL,
	is_con_id text NULL,
	restructure text NULL,
	l_abjf_porsi text NULL,
	l_abjf_rate text NULL,
	l_abjf_valdate text NULL,
	alt_limit_id text NULL,
	limit_reference text NULL,
	abjf_selldate text NULL,
	int_rate_type text NULL,
	alt_ld_id_2 text NULL,
	l_abjf_plafon text NULL,
	new_int_rate text NULL
);


-- landing_dq.ssab_coll_ld_schedule_define definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_ld_schedule_define;

CREATE TABLE landing_dq.ssab_coll_ld_schedule_define (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	dates text NULL,
	cycled_dates text NULL,
	forward_backward text NULL,
	sch_type text NULL,
	amount text NULL,
	rate text NULL,
	co_code text NULL,
	contract_id text NULL,
	currency text NULL,
	base_date_key text NULL,
	frequency text NULL,
	freq_code text NULL,
	sched_date text NULL,
	sched_type text NULL,
	advice_type text NULL,
	advice_date text NULL,
	prev_sched_type text NULL,
	prev_sched_date text NULL,
	override text NULL,
	record_status text NULL,
	curr_no text NULL,
	inputter text NULL,
	date_time text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL
);


-- landing_dq.ssab_coll_lmm_schedules definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_lmm_schedules;

CREATE TABLE landing_dq.ssab_coll_lmm_schedules (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	prin_amount_due text NULL,
	sched_amt text NULL,
	ld_id text NULL
);


-- landing_dq.ssab_coll_mm_insurance definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_mm_insurance;

CREATE TABLE landing_dq.ssab_coll_mm_insurance (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	l_bnk_acc text NULL,
	l_bnk_acc_name text NULL,
	customer_no text NULL,
	customer_name text NULL,
	category text NULL,
	category_description text NULL,
	l_ins_company text NULL,
	l_month_premium text NULL,
	l_ins_nominee text NULL,
	l_ins_claim_amt text NULL,
	principal text NULL,
	co_code text NULL,
	eq_rate_mm text NULL,
	mud_nisbah text NULL,
	mis_acct_officer text NULL,
	value_date text NULL,
	mud_tenor text NULL,
	maturity_date text NULL,
	final_maturity text NULL,
	customer_id text NULL,
	alt_mm_id text NULL,
	alt_dep_acct_id text NULL,
	prin_liq_acct text NULL,
	mis_acct_officer_1 text NULL,
	mm_orig_amount text NULL,
	mm_orig_date text NULL,
	status text NULL,
	alt_mm_id_1 text NULL
);


-- landing_dq.ssab_coll_pd_payment_due definition

-- Drop table

-- DROP TABLE landing_dq.ssab_coll_pd_payment_due;

CREATE TABLE landing_dq.ssab_coll_pd_payment_due (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	total_amt_to_repay text NULL,
	payment_dte_due text NULL,
	co_code text NULL,
	tot_od_type_amt text NULL,
	repayment_acct text NULL,
	asset_class text NULL,
	status text NULL,
	move_to_his text NULL,
	tot_ovrdue_type text NULL,
	ld_hb_dt text NULL
);


-- landing_dq.ssab_company definition

-- Drop table

-- DROP TABLE landing_dq.ssab_company;

CREATE TABLE landing_dq.ssab_company (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	company_name text NULL,
	name_address text NULL,
	mnemonic text NULL,
	language_code text NULL,
	local_country text NULL,
	local_region text NULL,
	local_currency text NULL,
	rate_system text NULL,
	customer_company text NULL,
	customer_mnemonic text NULL,
	default_cust_com text NULL,
	default_cust_mne text NULL,
	currency_company text NULL,
	currency_mnemonic text NULL,
	company_group text NULL,
	official_holiday text NULL,
	branch_holiday text NULL,
	batch_holiday text NULL,
	local_ref text NULL
);


-- landing_dq.ssab_eb_contract_balances definition

-- Drop table

-- DROP TABLE landing_dq.ssab_eb_contract_balances;

CREATE TABLE landing_dq.ssab_eb_contract_balances (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	accr_category text NULL,
	curr_asset_type text NULL,
	open_balance text NULL,
	currency text NULL,
	credit_mvmt text NULL,
	debit_mvmt text NULL,
	collateral text NULL,
	customer text NULL,
	co_code text NULL,
	type_sysdate text NULL,
	open_actual_bal text NULL
);


-- landing_dq.ssab_ext_collateral_type definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_collateral_type;

CREATE TABLE landing_dq.ssab_ext_collateral_type (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	sid_jenis_agunan text NULL,
	description text NULL
);


-- landing_dq.ssab_ext_collector definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_collector;

CREATE TABLE landing_dq.ssab_ext_collector (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	collector_name text NULL,
	area text NULL
);


-- landing_dq.ssab_ext_lmm_account_balances definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_lmm_account_balances;

CREATE TABLE landing_dq.ssab_ext_lmm_account_balances (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	outs_accrued_int text NULL,
	start_period_int text NULL,
	end_period_int text NULL,
	ac_int_rate text NULL,
	date_int_acc_to text NULL,
	actual_acc_amt text NULL,
	outs_over_due_int text NULL,
	committed_int text NULL,
	princ_int_bal text NULL
);


-- landing_dq.ssab_ext_orafin_param definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_orafin_param;

CREATE TABLE landing_dq.ssab_ext_orafin_param (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id_seq bigserial NOT NULL,
	report_id text NULL,
	line_no text NULL,
	set_of_books_name text NULL,
	user_je_rc_name text NULL,
	user_je_cat_name text NULL,
	accounting_date text NULL,
	currency_code text NULL,
	actual_flag text NULL,
	ccy_conv_date text NULL,
	user_ccy_conv_type text NULL,
	ccy_conv_rate text NULL,
	segment1 text NULL,
	segment2 text NULL,
	segment3 text NULL,
	segment4 text NULL,
	segment5 text NULL,
	segment6 text NULL,
	segment7 text NULL,
	segment8 text NULL,
	segment9 text NULL,
	segment10 text NULL,
	segment11 text NULL,
	entered_dr text NULL,
	entered_cr text NULL,
	accounted_dr text NULL,
	accounted_cr text NULL,
	reference1 text NULL,
	reference2 text NULL,
	reference4 text NULL,
	reference5 text NULL,
	reference10 text NULL,
	company_code text NULL,
	entity_code text NULL,
	cost_center text NULL,
	nature_account text NULL,
	product_code text NULL,
	separate_rak text NULL,
	je_line_number text NULL,
	bulan_data text NULL,
	tahun_data text NULL,
	user_orafin text NULL
);


-- landing_dq.ssab_ext_pv_asset_detail definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_pv_asset_detail;

CREATE TABLE landing_dq.ssab_ext_pv_asset_detail (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	profile_id text NULL,
	last_calc_date text NULL,
	calc_prov_amt text NULL,
	calc_prov_type text NULL,
	auto_class text NULL,
	collateral_amount text NULL
);


-- landing_dq.ssab_ext_re_stat_rep_line definition

-- Drop table

-- DROP TABLE landing_dq.ssab_ext_re_stat_rep_line;

CREATE TABLE landing_dq.ssab_ext_re_stat_rep_line (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	"type" text NULL,
	"desc" text NULL,
	total_accum text NULL,
	line_balance text NULL,
	asset_applic_id text NULL,
	asset1 text NULL,
	asset2 text NULL,
	asset3 text NULL,
	asset4 text NULL,
	asset5 text NULL,
	asset6 text NULL,
	asset7 text NULL,
	asset8 text NULL,
	asset9 text NULL,
	asset10 text NULL,
	asset11 text NULL,
	asset_type text NULL,
	proft_applic_id text NULL,
	profit1 text NULL,
	profit2 text NULL,
	profit3 text NULL,
	profit4 text NULL,
	profit5 text NULL,
	profit6 text NULL,
	profit7 text NULL,
	profit8 text NULL,
	profit9 text NULL,
	profit10 text NULL,
	profit11 text NULL
);


-- landing_dq.ssab_l_ckpn_abjf definition

-- Drop table

-- DROP TABLE landing_dq.ssab_l_ckpn_abjf;

CREATE TABLE landing_dq.ssab_l_ckpn_abjf (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	l_ckpn_abjf_id text NULL,
	"date" text NULL,
	ckpn_amount text NULL,
	ckpn_rate text NULL,
	asset_class text NULL,
	category text NULL,
	local_ref text NULL,
	last_upd_date text NULL,
	lst_ckpn_amount text NULL,
	last_asset_class text NULL
);


-- landing_dq.ssab_limit definition

-- Drop table

-- DROP TABLE landing_dq.ssab_limit;

CREATE TABLE landing_dq.ssab_limit (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	limit_currency text NULL,
	approval_date text NULL,
	expiry_date text NULL,
	online_limit_date text NULL,
	internal_amount text NULL,
	collateral_code text NULL,
	online_limit text NULL,
	commitm_amt text NULL,
	account text NULL,
	curr_no text NULL,
	date_time text NULL,
	co_code text NULL,
	tgl_pk_awal text NULL,
	tgl_pk_akhir text NULL,
	no_pk_limit text NULL,
	no_pk_limend text NULL,
	product_allowed text NULL,
	co_book text NULL,
	record_parent text NULL,
	dt_old_exp text NULL,
	dt_upd_limit text NULL,
	lbu_jn_guna text NULL,
	avail_amt text NULL,
	committed_flag text NULL,
	reducing_limit text NULL,
	gur_name text NULL,
	jenis_penjamin text NULL,
	gur_gol_penjami text NULL,
	gur_bagian_dija text NULL,
	gur_legal_id text NULL,
	gur_npwp text NULL,
	gur_street text NULL,
	collat_right text NULL,
	group_db text NULL,
	limit_product text NULL,
	lbu_pfolio text NULL,
	sid_kat_deb text NULL,
	lbu_sifat_kred text NULL,
	lbu_sektor_eko text NULL,
	lbu_kat_ukur text NULL,
	lbu_jenis_peng text NULL,
	lbu_or_guna text NULL,
	lb_jenis_kredit text NULL,
	sid_sifat_kredi text NULL,
	sid_jenis_peng text NULL,
	sid_sektor_econ text NULL,
	nil_proyek_bi text NULL,
	sid_lokasi_pryk text NULL,
	alt_limit_id text NULL,
	record_status text NULL,
	total_os text NULL,
	country_of_risk text NULL,
	country_percent text NULL,
	offered_until text NULL,
	review_frequency text NULL,
	adm_extension_date text NULL,
	proposal_date text NULL,
	limit_grade text NULL,
	grade_percent text NULL,
	notes text NULL,
	advised_amount text NULL,
	fixed_variable text NULL,
	coll_reqd_amt text NULL,
	coll_reqd_prcnt text NULL,
	up_to_period text NULL,
	period_amt text NULL,
	period_prcnt text NULL,
	maximum_secured text NULL,
	maximum_unsecured text NULL,
	maximum_total text NULL,
	other_secured text NULL,
	secured_amt text NULL,
	time_code text NULL,
	limit_band text NULL,
	sub_alloc_taken text NULL,
	sub_alloc_given text NULL,
	commt_amt_avail text NULL,
	s_al_tkn_ccy text NULL,
	s_al_tkn_amt text NULL,
	s_al_gvn_ccy text NULL,
	s_al_gvn_amt text NULL,
	commitm_ccy text NULL,
	os_ccy text NULL,
	os_amt text NULL,
	date_of_excess text NULL,
	amt_last_excess text NULL,
	date_last_moved text NULL,
	amt_last_moved text NULL,
	date_1st_excess text NULL,
	date_last_reval text NULL,
	original_limit text NULL,
	clean_risk text NULL,
	date_clrisk_exc text NULL,
	available_marker text NULL,
	allowed_cust text NULL,
	restricted_cust text NULL,
	allowed_ccy text NULL,
	allowed_amt text NULL,
	restricted_ccy text NULL,
	allowed_comp text NULL,
	restricted_comp text NULL,
	commodity text NULL,
	commodity_pcent text NULL,
	collat_code text NULL,
	collat_customer text NULL,
	collat_ccy text NULL,
	collat_amount text NULL,
	collat_percent text NULL,
	collat_location text NULL,
	collat_grade text NULL,
	collat_notes text NULL,
	reducing_sched text NULL,
	repay_freq text NULL,
	repay_number text NULL,
	repay_ccy text NULL,
	repay_amount text NULL,
	repay_end_date text NULL,
	repay_notes text NULL,
	acc_company text NULL,
	no_of_sub_allocs text NULL,
	fx_or_time_band text NULL,
	liability_number text NULL,
	credit_line text NULL,
	check_limit text NULL,
	consol_key text NULL,
	allow_netting text NULL,
	dispo_officer text NULL,
	online_update text NULL,
	increasing_type text NULL,
	increase_freq text NULL,
	increase_ccy text NULL,
	increase_amount text NULL,
	incr_end_date text NULL,
	gur_city text NULL,
	gur_street2 text NULL,
	gur_zip_code text NULL,
	gur_street3 text NULL,
	gur_province text NULL,
	reserved1 text NULL,
	reserved2 text NULL,
	reserved3 text NULL,
	reserved4 text NULL,
	charge_code text NULL,
	charge_amount text NULL,
	admin_fee_code text NULL,
	admin_fee_chrg text NULL,
	prk_chrg_acct text NULL,
	or_guna text NULL,
	unutil_acct text NULL,
	curr_unutil_amt text NULL,
	allow_unutil_cr text NULL,
	prev_unutil_acct text NULL,
	prev_unutil_amt text NULL,
	last_draw_date text NULL,
	created_from text NULL,
	limits_modified text NULL,
	util_account text NULL,
	curr_util_amt text NULL,
	prev_util_acct text NULL,
	prev_util_amt text NULL,
	alloc_work_id text NULL,
	reserved_2 text NULL,
	reserved_1 text NULL,
	override text NULL,
	inputter text NULL,
	authoriser text NULL,
	dept_code text NULL,
	auditor_code text NULL,
	audit_date_time text NULL,
	l_tgl_macet text NULL,
	l_sid_sbmct text NULL,
	l_ket_macet text NULL,
	l_tgl_res text NULL,
	l_no_res text NULL,
	l_tgl_res_awal text NULL,
	l_limit_order text NULL,
	l_tgl_loan text NULL,
	last_version text NULL,
	otor_version text NULL,
	l_sid_jnfas text NULL
);


-- landing_dq.ssab_mur_amt_his definition

-- Drop table

-- DROP TABLE landing_dq.ssab_mur_amt_his;

CREATE TABLE landing_dq.ssab_mur_amt_his (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	contract_id text NULL,
	his_type text NULL,
	plafond text NULL,
	sisa_tenor text NULL,
	record_status text NULL,
	tgl_realisasi text NULL,
	rate text NULL,
	angsur_amt text NULL
);


-- landing_dq.ssab_pd_balances definition

-- Drop table

-- DROP TABLE landing_dq.ssab_pd_balances;

CREATE TABLE landing_dq.ssab_pd_balances (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	record_start_date text NULL,
	currency text NULL,
	payment_status text NULL,
	previous_status text NULL,
	no_days_overdue text NULL,
	base_eff_date text NULL,
	base_amount text NULL,
	rate text NULL,
	post_start_date text NULL,
	post_end_date text NULL,
	rate2_eff_date text NULL,
	post2_start_date text NULL,
	post2_end_date text NULL,
	pen_calc_date text NULL,
	from_date_1 text NULL,
	to_date_1 text NULL,
	no_days_1 text NULL,
	base_amt_1 text NULL,
	original_amt text NULL,
	curr_os_amt text NULL,
	amt_type text NULL,
	create_date text NULL,
	loan_spread text NULL
);


-- landing_dq.ssab_re_stat_line_bal definition

-- Drop table

-- DROP TABLE landing_dq.ssab_re_stat_line_bal;

CREATE TABLE landing_dq.ssab_re_stat_line_bal (
	batch_date text NULL,
	insert_timestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_seq bigserial NOT NULL,
	source_system_code text NULL DEFAULT 'SSAB'::text,
	id text NULL,
	line_ccy_date text NULL,
	open_bal text NULL,
	open_bal_lcl text NULL,
	cr_movement text NULL,
	cr_mvmt_lcl text NULL,
	db_movement text NULL,
	db_mvmt_lcl text NULL,
	closing_bal text NULL,
	closing_bal_lcl text NULL,
	report_name text NULL,
	report_line text NULL,
	period_end_date text NULL,
	currency text NULL,
	system_date text NULL,
	mvmt_a_split text NULL,
	mvmt_p_split text NULL,
	mvmt_r_split text NULL,
	line_name text NULL,
	cr_mvmt_ytd text NULL,
	cr_mvmt_mth text NULL,
	cr_mvmt_ytd_lcl text NULL,
	cr_mvmt_mth_lcl text NULL,
	db_mvmt_ytd text NULL,
	db_mvmt_mth text NULL,
	db_mvmt_ytd_lcl text NULL,
	db_mvmt_mth_lcl text NULL
);