insert into ods_dq.customer 
(business_date,source_system_code,customer_identifier,crn_number,customer_branch_code,customer_open_date,customer_full_name,customer_short_name,customer_type_code,place_of_birth,date_of_birth,gender,marital_status,marital_status_description,number_of_dependent,religion_type_code,religion_type_description,residence_country_code,residence_country_description,origin_country_code,origin_country_description,identification_type_code,identification_number,npwp_number,job_title,office_name,office_phone_text,office_fax_number_text,employment_status,employment_start,last_education,mother_name,email_address,mobile_phone_number,home_phone_number,fax_number,prime_address_street_name,prime_address_rt_text,prime_address_rw_text,prime_address_kelurahan_text,prime_address_kecamatan_text,prime_address_city_text,prime_address_province_text,prime_address_dati2_text,prime_address_country_code,prime_address_postal_code,residential_status_code,residential_status_description,domicile_address_street_text,domicile_address_rt_text,domicile_address_rw_text,domicile_address_kelurahan_text,domicile_address_kecamatan_text,domicile_address_city_text,domicile_address_province_text,domicile_address_country_code,domicile_address_postal_code,office_address_street_text,office_address_rt_text,office_address_rw_text,office_address_kelurahan_text,office_address_kecamatan_text,office_address_city_text,office_address_province_text,office_address_country_code,office_address_postal_code_text,correspondence_address_street_text,correspondence_address_rt_text,correspondence_address_rw_text,correspondence_address_kelurahan_text,correspondence_address_kecamatan_text,correspondence_address_city_text,correspondence_address_province_text,correspondence_address_country_code,correspondence_address_postal_code_text,spouse_name,spouse_identification_number,spouse_date_of_birth,property_separation_agreement_flag,relatives_full_name,relatives_address_street_text,relatives_address_rt_text,relatives_address_rw_text,relatives_address_kelurahan_text,relatives_address_kecamatan_text,relatives_address_city_text,relatives_address_province_text,relatives_address_country_code,relatives_address_postal_code_text,relatives_mobile_phone_text,relatives_home_phone_text,customer_relatives_relationship_type_code,customer_relatives_relationship_type_description,legal_form_type_code,legal_form_description,judicial_approval_number_text,judicial_approval_date,deed_of_establishment_text,place_of_establishment_text,date_of_establishment_text,basic_budget_number_text,date_of_basic_budget_text,trade_business_license_text,certificate_of_company_registration_text,certificate_of_company_registration_date,last_certificate_of_company_registration_text,last_certificate_of_company_registration_date,shareholder1_name,shareholder1_share_amount_text,shareholder2_name,shareholder2_share_amount_text,shareholder3_name,shareholder3_share_amount_text,shareholder4_name,shareholder4_share_amount_text,official1_name,official1_title_text,official1_identification_number_text,official1_identification_expiry_date,official1_citizenship_text,official2_name,official2_job_position_text,official2_identification_number_text,official2_identification_expiry_date,official2_citizenship_text,official3_name,official3_job_position_text,official3_identification_number_text,official3_identification_expiry_date,official3_citizenship_text,official4_name,official4_job_position_text,official4_identification_number_text,official4_identification_expiry_date,official4_citizenship_text,official5_name,official5_job_position_text,official5_identification_number_text,official5_identification_expiry_date,official5_citizenship_text,reference_bank_name,reference_bank_account_type_text,reference_bank_account_number_text,net_income_amount_type_code,net_income_amount_type_description,net_outcome_amount,authorized_person_full_name,authorized_person_job_position_text,authorized_person_identification_number_text,authorized_person_telephone_number_text,authorized_person_email_address_text,certificate_of_company_registration_expiry_date,rating_institution_code,customer_rating_code,rating_date,go_public_flag,international_rating_institution_name,international_debtor_rating_name,international_rating_date,domestic_rating_institution_name,domestic_debtor_rating_name,domestic_rating_date,share_holding_percentage,economic_sector_type_code,current_income_type_code,current_income_type_description,source_of_fund_type_code,source_of_fund_type_description,opening_purpose_type_code,opening_purpose_description,industrial_sector_text,bank_relationship_type_code,bank_relationship_type_description,average_debet_transaction_amount,average_credit_transaction_amount,debet_transaction_count,credit_transaction_count,additional_income_type_code,additional_income_type_description,title_text,customer_mnemonic_text,customer_group_lbu_code,customer_group_lbu_description,goldeb_lbu_code,melanggar_bmpk_flag,melampaui_bmpk_flag,old_customer_number,customer_collectibility_code,loan_active_flag,officer_id,inputter,authorizer,customer_status,record_last_update_date,is_regulatory,ingestion_time,last_maker_by,last_maker_time,last_checker_by,last_checker_time,flag_validate,desc_validate,customer_type,customer_manual_risk_class,pep_flag,kyc_cash_deposit_limit,kyc_cash_deposit_frequency,kyc_non_cash_limit,kyc_non_cash_limit_frequency,kyc_cash_withdraw_limit,kyc_cash_withdraw_frequency,kyc_non_cash_withdraw,kyc_non_cash_frequency,occupation,debtor_category_code,customer_relationship_slik_code,customer_relationship_slik_description,customer_relationship_antasena_code,customer_relationship_antasena_description,certificate_of_company_registration_place,industrial_sector_text_2)
select
	cast(batch_date as date) as business_date ,
	cast('BSS' as varchar(3)) as source_system_code,
	cast(customer.customer_no as varchar(100)) as customer_identifier ,
	cast('' as varchar(100)) as crn_number ,
	cast(customer.company_book as varchar(50)) as customer_branch_code ,
	cast(case when customer.cus_open_date='' then null else customer.cus_open_date end as date) as customer_open_date ,
	cast(customer.name_1 as varchar(255)) as customer_full_name ,
	cast(customer.short_name as varchar(50)) as customer_short_name ,
	cast(case when customer.gender is not null and customer.gender<>'' then '01' else '02' end as varchar(50)) as customer_type_code ,
	cast(customer.place_of_birth as text) as place_of_birth ,
	cast(case when customer.date_of_birth='' then null else customer.date_of_birth end as date) as date_of_birth ,
	cast(customer.gender as varchar(1)) as gender ,
	cast(customer.marital_status as varchar(1)) as marital_status ,
	cast(null as varchar(50)) as marital_status_description ,
	cast(case when customer.no_of_dependents ='' then null else customer.no_of_dependents end as integer) as number_of_dependent ,
	cast(null as varchar(1)) as religion_type_code ,
	cast(null as varchar(50)) as religion_type_description ,
	cast(customer.residence as varchar(2)) as residence_country_code ,
	cast(null as varchar(50)) as residence_country_description ,
	cast(customer.nationality as varchar(2)) as origin_country_code ,
	cast(null as varchar(50)) as origin_country_description ,
	cast(customer.legal_doc_name as text) as identification_type_code ,
	cast(customer.legal_id as varchar(50)) as identification_number ,
	cast(customer.cus_npwp as varchar(50)) as npwp_number ,
	cast(customer.job_title as varchar(50)) as job_title ,
	cast(customer.employers_name as varchar(50)) as office_name ,
	cast(null as varchar(50)) as office_phone_text ,
	cast(null as varchar(50)) as office_fax_number_text ,
	cast(null as varchar(50)) as employment_status ,
	cast(null as date) as employment_start ,
	cast(customer.last_education as varchar(50)) as last_education ,
	cast(customer.mother_maid_nam as varchar(50)) as mother_name ,
	cast(customer.email_1 as varchar(50)) as email_address ,
	cast(customer.sms_1 as varchar(50)) as mobile_phone_number ,
	cast(customer.phone_1 as varchar(50)) as home_phone_number ,
	cast(null as varchar(50)) as fax_number ,
	cast(customer.street as varchar(50)) as prime_address_street_name ,
	cast(customer.ktp_rt as varchar(50)) as prime_address_rt_text ,
	cast(customer.ktp_rw as varchar(50)) as prime_address_rw_text ,
	cast(customer.ktp_kelurahan as varchar(50)) as prime_address_kelurahan_text ,
	cast(customer.ktp_kecamatan as varchar(50)) as prime_address_kecamatan_text ,
	cast(null as varchar(50)) as prime_address_city_text ,
	cast(null as varchar(50)) as prime_address_province_text ,
	cast(customer.sid_dati2debtor as text) as prime_address_dati2_text ,
	cast(null as varchar(50)) as prime_address_country_code ,
	cast(customer.post_code as varchar(50)) as prime_address_postal_code ,
	cast(customer.residence_status as varchar(1)) as residential_status_code ,
	cast(null as varchar(50)) as residential_status_description ,
	cast(null as varchar(50)) as domicile_address_street_text ,
	cast(null as varchar(50)) as domicile_address_rt_text ,
	cast(null as varchar(50)) as domicile_address_rw_text ,
	cast(null as varchar(50)) as domicile_address_kelurahan_text ,
	cast(null as varchar(50)) as domicile_address_kecamatan_text ,
	cast(null as varchar(50)) as domicile_address_city_text ,
	cast(null as varchar(50)) as domicile_address_province_text ,
	cast(null as varchar(50)) as domicile_address_country_code ,
	cast(null as varchar(50)) as domicile_address_postal_code ,
	cast(customer.employers_add as varchar(50)) as office_address_street_text ,
	cast(null as varchar(50)) as office_address_rt_text ,
	cast(null as varchar(50)) as office_address_rw_text ,
	cast(null as varchar(50)) as office_address_kelurahan_text ,
	cast(null as varchar(50)) as office_address_kecamatan_text ,
	cast(null as varchar(50)) as office_address_city_text ,
	cast(null as varchar(50)) as office_address_province_text ,
	cast(null as varchar(50)) as office_address_country_code ,
	cast(null as varchar(50)) as office_address_postal_code_text ,
	cast(null as varchar(50)) as correspondence_address_street_text ,
	cast(null as varchar(50)) as correspondence_address_rt_text ,
	cast(null as varchar(50)) as correspondence_address_rw_text ,
	cast(null as varchar(50)) as correspondence_address_kelurahan_text ,
	cast(null as varchar(50)) as correspondence_address_kecamatan_text ,
	cast(null as varchar(50)) as correspondence_address_city_text ,
	cast(null as varchar(50)) as correspondence_address_province_text ,
	cast(null as varchar(50)) as correspondence_address_country_code ,
	cast(null as varchar(50)) as correspondence_address_postal_code_text ,
	cast(customer.spouse_name as text) as spouse_name ,
	cast(customer.spouse_id as text) as spouse_identification_number ,
	cast(customer.spou_dt_of_birt as text) as spouse_date_of_birth ,
	cast(customer.l_pisah_harta as text) as property_separation_agreement_flag ,
	cast(null as varchar(50)) as relatives_full_name ,
	cast(null as varchar(50)) as relatives_address_street_text ,
	cast(null as varchar(50)) as relatives_address_rt_text ,
	cast(null as varchar(50)) as relatives_address_rw_text ,
	cast(null as varchar(50)) as relatives_address_kelurahan_text ,
	cast(null as varchar(50)) as relatives_address_kecamatan_text ,
	cast(null as varchar(50)) as relatives_address_city_text ,
	cast(null as varchar(50)) as relatives_address_province_text ,
	cast(null as varchar(50)) as relatives_address_country_code ,
	cast(null as varchar(50)) as relatives_address_postal_code_text ,
	cast(null as varchar(50)) as relatives_mobile_phone_text ,
	cast(null as varchar(50)) as relatives_home_phone_text ,
	cast(null as varchar(1)) as customer_relatives_relationship_type_code ,
	cast(null as varchar(50)) as customer_relatives_relationship_type_description ,
	cast(null as varchar(1)) as legal_form_type_code ,
	cast(null as varchar(50)) as legal_form_description ,
	cast(null as varchar(50)) as judicial_approval_number_text ,
	cast(null as date) as judicial_approval_date ,
	cast(null as varchar(50)) as deed_of_establishment_text ,
	cast(null as varchar(50)) as place_of_establishment_text ,
	cast(null as date) as date_of_establishment_text ,
	cast(null as varchar(50)) as basic_budget_number_text ,
	cast(null as date) as date_of_basic_budget_text ,
	cast(null as varchar(50)) as trade_business_license_text ,
	cast(customer.no_akta_awal as text) as certificate_of_company_registration_text ,
	cast(case when customer.tgl_akta_awal ='' then null else customer.tgl_akta_awal end as date) as certificate_of_company_registration_date ,
	cast(customer.no_akta_akhir as text) as last_certificate_of_company_registration_text ,
	cast(case when customer.tgl_akta_akhir ='' then null else customer.tgl_akta_akhir end as date) as last_certificate_of_company_registration_date ,
	cast(null as varchar(50)) as shareholder1_name ,
	cast(null as varchar(50)) as shareholder1_share_amount_text ,
	cast(null as varchar(50)) as shareholder2_name ,
	cast(null as varchar(50)) as shareholder2_share_amount_text ,
	cast(null as varchar(50)) as shareholder3_name ,
	cast(null as varchar(50)) as shareholder3_share_amount_text ,
	cast(null as varchar(50)) as shareholder4_name ,
	cast(null as varchar(50)) as shareholder4_share_amount_text ,
	cast(null as varchar(50)) as official1_name ,
	cast(null as varchar(50)) as official1_title_text ,
	cast(null as varchar(50)) as official1_identification_number_text ,
	cast(null as varchar(50)) as official1_identification_expiry_date ,
	cast(null as varchar(50)) as official1_citizenship_text ,
	cast(null as varchar(50)) as official2_name ,
	cast(null as varchar(50)) as official2_job_position_text ,
	cast(null as varchar(50)) as official2_identification_number_text ,
	cast(null as varchar(50)) as official2_identification_expiry_date ,
	cast(null as varchar(50)) as official2_citizenship_text ,
	cast(null as varchar(50)) as official3_name ,
	cast(null as varchar(50)) as official3_job_position_text ,
	cast(null as varchar(50)) as official3_identification_number_text ,
	cast(null as varchar(50)) as official3_identification_expiry_date ,
	cast(null as varchar(50)) as official3_citizenship_text ,
	cast(null as varchar(50)) as official4_name ,
	cast(null as varchar(50)) as official4_job_position_text ,
	cast(null as varchar(50)) as official4_identification_number_text ,
	cast(null as varchar(50)) as official4_identification_expiry_date ,
	cast(null as varchar(50)) as official4_citizenship_text ,
	cast(null as varchar(50)) as official5_name ,
	cast(null as varchar(50)) as official5_job_position_text ,
	cast(null as varchar(50)) as official5_identification_number_text ,
	cast(null as varchar(50)) as official5_identification_expiry_date ,
	cast(null as varchar(50)) as official5_citizenship_text ,
	cast(null as varchar(50)) as reference_bank_name ,
	cast(null as varchar(50)) as reference_bank_account_type_text ,
	cast(null as varchar(50)) as reference_bank_account_number_text ,
	cast(customer.kyc_incom_rng as varchar(2)) as net_income_amount_type_code ,
	cast(null as varchar(50)) as net_income_amount_type_description ,
	cast(customer.net_monthly_out as text) as net_outcome_amount ,
	cast(null as varchar(50)) as authorized_person_full_name ,
	cast(null as varchar(50)) as authorized_person_job_position_text ,
	cast(null as varchar(50)) as authorized_person_identification_number_text ,
	cast(null as varchar(50)) as authorized_person_telephone_number_text ,
	cast(null as varchar(50)) as authorized_person_email_address_text ,
	cast(null as date) as certificate_of_company_registration_expiry_date ,
	cast(customer.sid_lembaga as text) as rating_institution_code ,
	cast(customer.sid_rating_deb as text) as customer_rating_code ,
	cast(case when customer.sid_rating_tgl='' then null else customer.sid_rating_tgl end as text) as rating_date ,
	cast(customer.sid_go_public as text) as go_public_flag ,
	cast(null as varchar(50)) as international_rating_institution_name ,
	cast(null as varchar(50)) as international_debtor_rating_name ,
	cast(null as date) as international_rating_date ,
	cast(null as varchar(50)) as domestic_rating_institution_name ,
	cast(null as varchar(50)) as domestic_debtor_rating_name ,
	cast(null as date) as domestic_rating_date ,
	cast(null as varchar(50)) as share_holding_percentage ,
	cast(customer.sid_sektor_econ as varchar(10)) as economic_sector_type_code ,
	cast(customer.kyc_revenue as varchar(1)) as current_income_type_code ,
	cast(null as varchar(50)) as current_income_type_description ,
	cast(customer.kyc_income_src as varchar(1)) as source_of_fund_type_code ,
	cast(null as varchar(50)) as source_of_fund_type_description ,
	cast(customer.kyc_purpose_acc as varchar(1)) as opening_purpose_type_code ,
	cast(null as varchar(50)) as opening_purpose_description ,
	cast(z.lbu_sektor_eko as varchar(50)) as industrial_sector_text ,
	cast(customer.sid_related as varchar(1)) as bank_relationship_type_code ,
	cast(null as varchar(50)) as bank_relationship_type_description ,
	cast(null as varchar(50)) as average_debet_transaction_amount ,
	cast(null as varchar(50)) as average_credit_transaction_amount ,
	cast(null as varchar(50)) as debet_transaction_count ,
	cast(null as varchar(50)) as credit_transaction_count ,
	cast(null as varchar(1)) as additional_income_type_code ,
	cast(null as varchar(50)) as additional_income_type_description ,
	cast(null as varchar(50)) as title_text ,
	cast(null as varchar(50)) as customer_mnemonic_text ,
	cast(customer.sid_group_id as varchar(50)) as customer_group_lbu_code ,
	cast(customer.sid_group_name as varchar(50)) as customer_group_lbu_description ,
	cast(customer.lbu_gol_deb as text) as goldeb_lbu_code ,
	cast(customer.sid_melanggar as text) as melanggar_bmpk_flag ,
	cast(customer.sid_melampaui as text) as melampaui_bmpk_flag ,
	cast(null as varchar(50)) as old_customer_number ,
	coalesce(cast(ld.asset_class as varchar(1)),'') as customer_collectibility_code ,
	cast(case when ld.customer_id is not null then '1' else '0' end as text) as loan_active_flag , 
	cast(customer.account_officer as varchar(50)) as officer_id ,
	cast(null as varchar(50)) as inputter ,
	cast(null as varchar(50)) as authorizer ,
	cast(left(customer.customer_type,1) as varchar(1)) as customer_status,
	to_timestamp('20'||customer.date_time, 'YYYYMMDDHH24MI') as record_last_update_date ,
	cast('0' as text) as is_regulatory ,
	cast(current_timestamp as timestamp) as ingestion_time ,
	cast(null as text) as last_maker_by ,
	cast(null as text) as last_maker_time ,
	cast(null as text) as last_checker_by ,
	cast(null as text) as last_checker_time ,
	cast(null as text) as flag_validate ,
	cast(null as text) as desc_validate ,
	cast(case when customer.gender is not null and customer.gender <> '' then 'INDIVIDU' else 'CORPORATE' end as text) as customer_type ,
	cast(customer.manual_risk_class as text) as customer_manual_risk_class ,
	'' as pep_flag
	,cast(nullif(case 
		when kyc_cash_dep_li ='' then null 
		else case when right(kyc_cash_dep_li,3)='.00' then regexp_replace(regexp_replace(replace(kyc_cash_dep_li,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(kyc_cash_dep_li,'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2))  as kyc_cash_deposit_limit
	,cast(case when regexp_replace(kyc_cash_dep_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_cash_dep_fq, '[^0-9]+', '', 'g') end as int) as kyc_cash_deposit_frequency
	,cast(nullif(case 
		when kyc_noncash_lim ='' then null 
		else case when right(kyc_noncash_lim,3)='.00' then regexp_replace(regexp_replace(replace(kyc_noncash_lim,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(kyc_noncash_lim,'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2)) as kyc_non_cash_limit
	,cast(case when regexp_replace(kyc_noncash_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_noncash_fq, '[^0-9]+', '', 'g') end as int) as kyc_non_cash_limit_frequency
	,cast(nullif(case 
		when kyc_cash_wd_lim ='' then null 
		else case when right(kyc_cash_wd_lim,3)='.00' then regexp_replace(regexp_replace(replace(kyc_cash_wd_lim,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(replace(kyc_cash_wd_lim,'.',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2))  as kyc_cash_withdraw_limit
	,cast(case when regexp_replace(kyc_cash_wd_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_cash_wd_fq, '[^0-9]+', '', 'g') end as int) as kyc_cash_withdraw_frequency
	,cast(nullif(case 
		when kyc_non_cash_wd ='' then null 
		else case when right(kyc_non_cash_wd,3)='.00' then regexp_replace(regexp_replace(replace(kyc_non_cash_wd,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(replace(kyc_non_cash_wd,'.',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2)) as kyc_non_cash_withdraw
	,cast(case when regexp_replace(kyc_noncash_fqu, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_noncash_fqu, '[^0-9]+', '', 'g') end as int) as kyc_non_cash_frequency
	,cast(customer.occupation as varchar(100)) as occupation,
	cast(case when customer.sid_gelar='' then '00' else right(customer.sid_gelar,2) end as text) as debtor_category_code,
	cast(customer.sid_hub_bank as text) as customer_relationship_slik_code,
	cast(ref_slik.short_description as text) customer_relationship_slik_description,
	cast(null as text) as customer_relationship_antasena_code,
	cast(null as text) as customer_relationship_antasena_description,
	cast(case when customer.place_of_birth ='' then case when customer.sid_tmp_akte_ak ='' then customer.ktp_kelurahan else customer.sid_tmp_akte_ak end else null end as text) certificate_of_company_registration_place,
	cast(j.lbu_sektor_eko as varchar(50)) as industrial_sector_text_2
from landing_dq.bss_customer customer
left join (select customer_id, max(cast(case when asset_class='' then null else asset_class end as int)) as asset_class from landing.bss_ld group by customer_id) ld on customer.customer_no = ld.customer_id
left join (
	select customer_id, lbu_sektor_eko from (
		select customer_id, substr(lbu_sektor_eko,1,6) lbu_sektor_eko ,row_number() over(partition by customer_id order by customer_id) rn from (
			select 
			distinct
			substr(id,1,position('.' in id)-1) as customer_id,
			lbu_sektor_eko
			from landing_dq.bss_limit where lbu_sektor_eko <> ''
			) x
		) y
	where rn = 1
	) z on customer.id = z.customer_id
left join (
	select customer_id, lbu_sektor_eko from (
		select customer_id, substr(lbu_sektor_eko,1,6) lbu_sektor_eko,row_number() over(partition by customer_id order by customer_id) rn from (
			select 
			distinct
			substr(id,1,position('.' in id)-1) as customer_id,
			lbu_sektor_eko
			from landing_dq.bss_limit where lbu_sektor_eko <> ''
			) h
		) i
	where rn = 2
	) j on customer.id = j.customer_id
left join ods_dq.ref_slik_hub_pelapor ref_slik on trim(customer.sid_hub_bank) = ref_slik.kode

union all

select
	cast(batch_date as date) as business_date ,
	cast('SSAB' as varchar(3)) as source_system_code,
	cast(customer.id as varchar(100)) as customer_identifier , --kolomnya ga ada
	cast('' as varchar(100)) as crn_number ,
	cast(customer.company_book as varchar(50)) as customer_branch_code ,
	cast(case when customer.cus_open_date='' then null else customer.cus_open_date end as date) as customer_open_date ,
	cast(customer.name_1 as varchar(255)) as customer_full_name ,
	cast(customer.short_name as varchar(50)) as customer_short_name ,
	cast(case when customer.gender is not null and customer.gender<>'' then '01' else '02' end as varchar(50)) as customer_type_code ,
	cast(customer.place_of_birth as text) as place_of_birth ,
	cast(case when customer.date_of_birth='' then null else customer.date_of_birth end as date) as date_of_birth ,
	cast(customer.gender as varchar(1)) as gender ,
	cast(customer.marital_status as varchar(1)) as marital_status ,
	cast(null as varchar(50)) as marital_status_description ,
	cast(case when customer.no_of_dependents ='' then null else customer.no_of_dependents end as integer) as number_of_dependent ,
	cast(null as varchar(1)) as religion_type_code ,
	cast(null as varchar(50)) as religion_type_description ,
	cast(customer.residence as varchar(2)) as residence_country_code ,
	cast(null as varchar(50)) as residence_country_description ,
	cast(customer.nationality as varchar(2)) as origin_country_code ,
	cast(null as varchar(50)) as origin_country_description ,
	cast(customer.legal_doc_name as text) as identification_type_code ,
	cast(customer.legal_id as varchar(50)) as identification_number ,
	cast(customer.cus_npwp as varchar(50)) as npwp_number ,
	cast(customer.job_title as varchar(50)) as job_title ,
	cast(customer.employers_name as varchar(50)) as office_name ,
	cast(null as varchar(50)) as office_phone_text ,
	cast(null as varchar(50)) as office_fax_number_text ,
	cast(null as varchar(50)) as employment_status ,
	cast(null as date) as employment_start ,
	cast(customer.last_education as varchar(50)) as last_education ,
	cast(customer.mother_maid_nam as varchar(50)) as mother_name ,
	cast(customer.email_1 as varchar(50)) as email_address ,
	cast(customer.sms_1 as varchar(50)) as mobile_phone_number ,
	cast(customer.phone_1 as varchar(50)) as home_phone_number ,
	cast(null as varchar(50)) as fax_number ,
cast(case when customer.address ='' then customer.street else customer.address end as varchar(50)) as prime_address_street_name,
	cast(customer.ktp_rt as varchar(50)) as prime_address_rt_text ,
	cast(customer.ktp_rw as varchar(50)) as prime_address_rw_text ,
	cast(customer.ktp_kelurahan as varchar(50)) as prime_address_kelurahan_text ,
	cast(customer.ktp_kacamatan as varchar(50)) as prime_address_kecamatan_text ,
	cast(null as varchar(50)) as prime_address_city_text ,
	cast(null as varchar(50)) as prime_address_province_text ,
	cast(customer.sid_dati2_debtor as text) as prime_address_dati2_text ,
	cast(null as varchar(50)) as prime_address_country_code ,
	cast(customer.post_code as varchar(50)) as prime_address_postal_code ,
	cast(customer.residence_status as varchar(1)) as residential_status_code ,
	cast(null as varchar(50)) as residential_status_description ,
	cast(null as varchar(50)) as domicile_address_street_text ,
	cast(null as varchar(50)) as domicile_address_rt_text ,
	cast(null as varchar(50)) as domicile_address_rw_text ,
	cast(null as varchar(50)) as domicile_address_kelurahan_text ,
	cast(null as varchar(50)) as domicile_address_kecamatan_text ,
	cast(null as varchar(50)) as domicile_address_city_text ,
	cast(null as varchar(50)) as domicile_address_province_text ,
	cast(null as varchar(50)) as domicile_address_country_code ,
	cast(null as varchar(50)) as domicile_address_postal_code ,
	cast(customer.employers_add as varchar(50)) as office_address_street_text ,
	cast(null as varchar(50)) as office_address_rt_text ,
	cast(null as varchar(50)) as office_address_rw_text ,
	cast(null as varchar(50)) as office_address_kelurahan_text ,
	cast(null as varchar(50)) as office_address_kecamatan_text ,
	cast(null as varchar(50)) as office_address_city_text ,
	cast(null as varchar(50)) as office_address_province_text ,
	cast(null as varchar(50)) as office_address_country_code ,
	cast(null as varchar(50)) as office_address_postal_code_text ,
	cast(null as varchar(50)) as correspondence_address_street_text ,
	cast(null as varchar(50)) as correspondence_address_rt_text ,
	cast(null as varchar(50)) as correspondence_address_rw_text ,
	cast(null as varchar(50)) as correspondence_address_kelurahan_text ,
	cast(null as varchar(50)) as correspondence_address_kecamatan_text ,
	cast(null as varchar(50)) as correspondence_address_city_text ,
	cast(null as varchar(50)) as correspondence_address_province_text ,
	cast(null as varchar(50)) as correspondence_address_country_code ,
	cast(null as varchar(50)) as correspondence_address_postal_code_text ,
	cast(customer.spouse_name as text) as spouse_name ,
	cast(customer.spouse_id as text) as spouse_identification_number ,
	cast(customer.spou_dt_of_birt as text) as spouse_date_of_birth ,
	cast(customer.l_pisah_harta as text) as property_separation_agreement_flag ,
	cast(null as varchar(50)) as relatives_full_name ,
	cast(null as varchar(50)) as relatives_address_street_text ,
	cast(null as varchar(50)) as relatives_address_rt_text ,
	cast(null as varchar(50)) as relatives_address_rw_text ,
	cast(null as varchar(50)) as relatives_address_kelurahan_text ,
	cast(null as varchar(50)) as relatives_address_kecamatan_text ,
	cast(null as varchar(50)) as relatives_address_city_text ,
	cast(null as varchar(50)) as relatives_address_province_text ,
	cast(null as varchar(50)) as relatives_address_country_code ,
	cast(null as varchar(50)) as relatives_address_postal_code_text ,
	cast(null as varchar(50)) as relatives_mobile_phone_text ,
	cast(null as varchar(50)) as relatives_home_phone_text ,
	cast(null as varchar(1)) as customer_relatives_relationship_type_code ,
	cast(null as varchar(50)) as customer_relatives_relationship_type_description ,
	cast(null as varchar(1)) as legal_form_type_code ,
	cast(null as varchar(50)) as legal_form_description ,
	cast(null as varchar(50)) as judicial_approval_number_text ,
	cast(null as date) as judicial_approval_date ,
	cast(null as varchar(50)) as deed_of_establishment_text ,
	cast(null as varchar(50)) as place_of_establishment_text ,
	cast(null as date) as date_of_establishment_text ,
	cast(null as varchar(50)) as basic_budget_number_text ,
	cast(null as date) as date_of_basic_budget_text ,
	cast(null as varchar(50)) as trade_business_license_text ,
cast(customer.kyc_akte_no as text) as certificate_of_company_registration_text ,
cast(nullif(customer.sid_tgl_akte_ak,'') as date) as certificate_of_company_registration_date,
cast(customer.kyc_akte_no as text) as last_certificate_of_company_registration_text,
cast(nullif(customer.sid_tgl_akte_ak,'') as date) as last_certificate_of_company_registration_date,
	cast(null as varchar(50)) as shareholder1_name ,
	cast(null as varchar(50)) as shareholder1_share_amount_text ,
	cast(null as varchar(50)) as shareholder2_name ,
	cast(null as varchar(50)) as shareholder2_share_amount_text ,
	cast(null as varchar(50)) as shareholder3_name ,
	cast(null as varchar(50)) as shareholder3_share_amount_text ,
	cast(null as varchar(50)) as shareholder4_name ,
	cast(null as varchar(50)) as shareholder4_share_amount_text ,
	cast(null as varchar(50)) as official1_name ,
	cast(null as varchar(50)) as official1_title_text ,
	cast(null as varchar(50)) as official1_identification_number_text ,
	cast(null as varchar(50)) as official1_identification_expiry_date ,
	cast(null as varchar(50)) as official1_citizenship_text ,
	cast(null as varchar(50)) as official2_name ,
	cast(null as varchar(50)) as official2_job_position_text ,
	cast(null as varchar(50)) as official2_identification_number_text ,
	cast(null as varchar(50)) as official2_identification_expiry_date ,
	cast(null as varchar(50)) as official2_citizenship_text ,
	cast(null as varchar(50)) as official3_name ,
	cast(null as varchar(50)) as official3_job_position_text ,
	cast(null as varchar(50)) as official3_identification_number_text ,
	cast(null as varchar(50)) as official3_identification_expiry_date ,
	cast(null as varchar(50)) as official3_citizenship_text ,
	cast(null as varchar(50)) as official4_name ,
	cast(null as varchar(50)) as official4_job_position_text ,
	cast(null as varchar(50)) as official4_identification_number_text ,
	cast(null as varchar(50)) as official4_identification_expiry_date ,
	cast(null as varchar(50)) as official4_citizenship_text ,
	cast(null as varchar(50)) as official5_name ,
	cast(null as varchar(50)) as official5_job_position_text ,
	cast(null as varchar(50)) as official5_identification_number_text ,
	cast(null as varchar(50)) as official5_identification_expiry_date ,
	cast(null as varchar(50)) as official5_citizenship_text ,
	cast(null as varchar(50)) as reference_bank_name ,
	cast(null as varchar(50)) as reference_bank_account_type_text ,
	cast(null as varchar(50)) as reference_bank_account_number_text ,
cast(customer.kyc_incom_rng as varchar(2)) as net_income_amount_type_code,
	cast(null as varchar(50)) as net_income_amount_type_description ,
	cast(customer.net_monthly_out as text) as net_outcome_amount ,
	cast(null as varchar(50)) as authorized_person_full_name ,
	cast(null as varchar(50)) as authorized_person_job_position_text ,
	cast(null as varchar(50)) as authorized_person_identification_number_text ,
	cast(null as varchar(50)) as authorized_person_telephone_number_text ,
	cast(null as varchar(50)) as authorized_person_email_address_text ,
	cast(null as date) as certificate_of_company_registration_expiry_date ,
cast(customer.sid_lembanga as text) as rating_institution_code,
	cast(customer.sid_rating_deb as text) as customer_rating_code ,
	cast(case when customer.sid_rating_tgl='' then null else customer.sid_rating_tgl end as text) as rating_date ,
	cast(customer.sid_go_public as text) as go_public_flag ,
	cast(null as varchar(50)) as international_rating_institution_name ,
	cast(null as varchar(50)) as international_debtor_rating_name ,
	cast(null as date) as international_rating_date ,
	cast(null as varchar(50)) as domestic_rating_institution_name ,
	cast(null as varchar(50)) as domestic_debtor_rating_name ,
	cast(null as date) as domestic_rating_date ,
	cast(null as varchar(50)) as share_holding_percentage ,
	cast(customer.sid_sektor_econ as varchar(10)) as economic_sector_type_code ,
	cast(customer.kyc_revenue as varchar(1)) as current_income_type_code ,
	cast(null as varchar(50)) as current_income_type_description ,
	cast(customer.kyc_income_src as varchar(1)) as source_of_fund_type_code ,
	cast(null as varchar(50)) as source_of_fund_type_description ,
	cast(customer.kyc_purpose_acc as varchar(1)) as opening_purpose_type_code ,
	cast(null as varchar(50)) as opening_purpose_description ,
	cast(z.lbu_sektor_eko as varchar(50)) as industrial_sector_text ,
	cast(customer.sid_related as varchar(1)) as bank_relationship_type_code ,
	cast(null as varchar(50)) as bank_relationship_type_description ,
	cast(null as varchar(50)) as average_debet_transaction_amount ,
	cast(null as varchar(50)) as average_credit_transaction_amount ,
	cast(null as varchar(50)) as debet_transaction_count ,
	cast(null as varchar(50)) as credit_transaction_count ,
	cast(null as varchar(1)) as additional_income_type_code ,
	cast(null as varchar(50)) as additional_income_type_description ,
	cast(null as varchar(50)) as title_text ,
	cast(null as varchar(50)) as customer_mnemonic_text ,
	cast(customer.sid_group_id as varchar(50)) as customer_group_lbu_code ,
	cast(customer.sid_group_name as varchar(50)) as customer_group_lbu_description ,
	cast(customer.lbu_gol_deb as text) as goldeb_lbu_code ,
	cast(customer.sid_malanggar as text) as melanggar_bmpk_flag ,
	cast(customer.sid_melampaui as text) as melampaui_bmpk_flag ,
	cast(null as varchar(50)) as old_customer_number ,
	coalesce(cast(ld.asset_class as varchar(1)),'') as customer_collectibility_code ,
	cast(case when ld.customer_id is not null then '1' else '0' end as text) as loan_active_flag , 
	cast(customer.account_officer as varchar(50)) as officer_id ,
	cast(null as varchar(50)) as inputter ,
	cast(null as varchar(50)) as authorizer ,
	cast(left(customer.customer_type,1) as varchar(1)) as customer_status,
	to_timestamp('20'||customer.date_time, 'YYYYMMDDHH24MI') as record_last_update_date ,
	cast('0' as text) as is_regulatory ,
	cast(current_timestamp as timestamp) as ingestion_time ,
	cast(null as text) as last_maker_by ,
	cast(null as text) as last_maker_time ,
	cast(null as text) as last_checker_by ,
	cast(null as text) as last_checker_time ,
	cast(null as text) as flag_validate ,
	cast(null as text) as desc_validate ,
	cast(case when customer.gender is not null and customer.gender <> '' then 'INDIVIDU' else 'CORPORATE' end as text) as customer_type ,
	cast('' as text) as customer_manual_risk_class ,
	'' as pep_flag
	,cast(nullif(case 
		when kyc_cash_dep_li ='' then null 
		else case when right(kyc_cash_dep_li,3)='.00' then regexp_replace(regexp_replace(replace(kyc_cash_dep_li,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(kyc_cash_dep_li,'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2))  as kyc_cash_deposit_limit
	,cast(case when regexp_replace(kyc_cash_dep_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_cash_dep_fq, '[^0-9]+', '', 'g') end as int) as kyc_cash_deposit_frequency
	,cast(nullif(case 
		when kyc_noncash_lim ='' then null 
		else case when right(kyc_noncash_lim,3)='.00' then regexp_replace(regexp_replace(replace(kyc_noncash_lim,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(kyc_noncash_lim,'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2)) as kyc_non_cash_limit
	,cast(case when regexp_replace(kyc_noncash_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_noncash_fq, '[^0-9]+', '', 'g') end as int) as kyc_non_cash_limit_frequency
	,cast(nullif(case 
		when kyc_cash_wd_lim ='' then null 
		else case when right(kyc_cash_wd_lim,3)='.00' then regexp_replace(regexp_replace(replace(kyc_cash_wd_lim,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(replace(kyc_cash_wd_lim,'.',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2))  as kyc_cash_withdraw_limit
	,cast(case when regexp_replace(kyc_cash_wd_fq, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_cash_wd_fq, '[^0-9]+', '', 'g') end as int) as kyc_cash_withdraw_frequency
	,cast(nullif(case 
		when kyc_non_cash_wd ='' then null 
		else case when right(kyc_non_cash_wd,3)='.00' then regexp_replace(regexp_replace(replace(kyc_non_cash_wd,'.00',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') else regexp_replace(regexp_replace(replace(kyc_non_cash_wd,'.',''),'[^\w]+','','g'),'[^0-9]+', '', 'g') end
	end,'') as decimal(28,2)) as kyc_non_cash_withdraw
	,cast(case when regexp_replace(kyc_noncash_fqu, '[^0-9]+', '', 'g') ='' then null else regexp_replace(kyc_noncash_fqu, '[^0-9]+', '', 'g') end as int) as kyc_non_cash_frequency
	,cast(customer.occupation as varchar(100)) as occupation,
	cast(case when customer.sid_gelar='' then '00' else right(customer.sid_gelar,2) end as text) as debtor_category_code,
	cast(customer.sid_hub_bank as text) as customer_relationship_slik_code,
	cast(ref_slik.short_description as text) customer_relationship_slik_description,
	cast(null as text) as customer_relationship_antasena_code,
	cast(null as text) as customer_relationship_antasena_description,
cast(case when customer.place_of_birth = '' then customer.sid_tempat_akte else '' end as text) as certificate_of_company_registration_place,
	cast(j.lbu_sektor_eko as varchar(50)) as industrial_sector_text_2
from landing_dq.ssab_coll_customer2 customer
left join (select customer_id, max(cast(case when asset_class='' then null else asset_class end as int)) as asset_class from landing.bss_ld group by customer_id) ld on customer.id = ld.customer_id
left join (
	select customer_id, lbu_sektor_eko from (
		select customer_id, substr(lbu_sektor_eko,1,6) lbu_sektor_eko ,row_number() over(partition by customer_id order by customer_id) rn from (
			select 
			distinct
			substr(id,1,position('.' in id)-1) as customer_id,
			lbu_sektor_eko
			from landing_dq.ssab_limit where lbu_sektor_eko <> ''
			) x
		) y
	where rn = 1
	) z on customer.id = z.customer_id
left join (
	select customer_id, lbu_sektor_eko from (
		select customer_id, substr(lbu_sektor_eko,1,6) lbu_sektor_eko,row_number() over(partition by customer_id order by customer_id) rn from (
			select 
			distinct
			substr(id,1,position('.' in id)-1) as customer_id,
			lbu_sektor_eko
			from landing_dq.ssab_limit where lbu_sektor_eko <> ''
			) h
		) i
	where rn = 2
	) j on customer.id = j.customer_id
left join ods_dq.ref_slik_hub_pelapor ref_slik on trim(customer.sid_hub_bank) = ref_slik.kode