CREATE OR REPLACE PROCEDURE landing.sp_truncate_landing()
 LANGUAGE plpgsql
AS $procedure$
begin
	-- T24
	truncate table landing.bss_account restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_account_closed restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_account_closure restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_account_credit_int restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_account_prk restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_categ_entry restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_category restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_collateral restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_collateral_right restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_company restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_currency restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_customer restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_de_address restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_eb_contract_balances restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_funds_transfer restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_kyc_sumber_dana restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_lbu_sektor_economy restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_ld restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_ld_sub_product restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_limit restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_md_deal restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_pd restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_pd_payment_due restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_re_consol_spec_entry restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_re_stat_line_bal restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_re_stat_rep_line restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_repo restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_sc_trading_position restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_sec_acc_master restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_sec_trade restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_sector restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_security_master restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_security_position restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_stmt_entry restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_stmt_entry_detail restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_teller_transaction restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_transaction restart identity;
    PERFORM pg_sleep(3);
	truncate table landing.bss_transaction_teller restart identity;
    PERFORM pg_sleep(3);
end;$procedure$
;